tsedio/tsed

src/server/server-loader.ts
* fix two places of typo
* add two proxy methods for `ServerLoader`
=> add two proxy methods and fix typo

docs/tutorials/aws.md
a review of the aws page copy
plus, added some missing information
=> improve aws docs

docs/configuration.md, docs/getting-started.md, src/server/class/ServerSettingsProvider.ts, src/server/services/ServerSettingsService.ts, test/integration/app/app.ts, test/units/server/services/ServerSettings.spec.ts
=> fix(settings): Fix interpolation with the ${rootDir}

src/mvc/class/HandlerBuilder.ts, test/units/mvc/class/HandlerBuilder.spec.ts
Fix server crashes when an object or an error have circular dependency.
Closes: #96
=> fix(handler): Fix server crashes

docs/configuration.md
|---|---|---|
Documentation| Ready 
****
I think tsExpressHandleStart was changed to tsedReqStart. So I changed configuration.md.
List related PRs against other branches:
branch | PR
|---|---|
fix_log_request_response | #100
=> docs(configuration): change tsExpressHandleStart to tsedReqStart.

src/mvc/components/GlobalErrorHandlerMiddleware.ts, src/mvc/components/ResponseViewMiddleware.ts, src/mvc/decorators/header.ts, src/mvc/decorators/method/contentType.ts, src/mvc/decorators/method/location.ts, src/mvc/decorators/method/redirect.ts, src/mvc/decorators/method/status.ts, test/units/mvc/components/GlobalErrorHandlerMiddleware.spec.ts, test/units/mvc/components/ResponseViewMiddleware.spec.ts, test/units/mvc/decorators/method/contentType.spec.ts, test/units/mvc/decorators/method/status.spec.ts
---|---|---
Chore | Ready | No
****
Closes: #103
=> chore: Remove headersSent condition in all middlewares

src/mvc/components/LogIncomingRequestMiddleware.ts
---|---|---
Refactoring | Ready | Yes
****
Move log start into a method to facilitate the override logger.
Closes: #135
=> fix: Refactoring log start.

package.json, src/di/registries/ProviderRegistry.ts, src/di/services/InjectorService.ts, src/filters/registries/FilterRegistry.ts, src/filters/services/FilterService.ts, src/mvc/registries/ControllerRegistry.ts, src/mvc/registries/MiddlewareRegistry.ts, src/mvc/services/ControllerService.ts, src/mvc/services/MiddlewareService.ts
---|---|---
Chore | Ready | No
=> chore: Remove ProxyRegistry class

docs/docs/converters.md, src/filters/registries/FilterRegistry.ts, src/jsonschema/class/PropertyMetadata.ts, src/jsonschema/decorators/jsonProperty.ts, src/jsonschema/decorators/propertyName.ts, src/jsonschema/decorators/propertyType.ts, src/jsonschema/index.ts, src/jsonschema/registries/JsonSchemesRegistry.ts, src/jsonschema/registries/PropertyRegistry.ts, test/helper/classes.ts, test/units/jsonschema/class/PropertyMetadata.spec.ts, test/units/jsonschema/decorators/jsonProperty.spec.ts, test/units/jsonschema/decorators/propertyName.spec.ts, test/units/jsonschema/decorators/propertyType.spec.ts, test/units/jsonschema/registries/PropertyRegistry.spec.ts, test/units/jsonschema/services/JsonSchemesService.spec.ts
---|---|---
****
- fix bug on jsonschema
- add Property alias decorator
- add PropertyName decorator
- add PropertyType decorator
```typescript
class EventModel {
@Required()
name: string;
@PropertyName('startDate')
startDate: Date;
@Property({name: 'end-date'})
endDate: Date;
@PropertyType(Task)
@Required()
@Allow(null)
tasks: TaskModel[];
}
class TaskModel {
@Required()
subject: string;
@Property()
rate: number;
}
```
=> feat(jsonschema): Add Property, PropertyName, PropertyType

docs/tutorials/upload-files-with-multer.md, package.json, src/multipartfiles/decorators/multipartFile.ts, src/multipartfiles/index.ts, src/multipartfiles/middlewares/MultipartFileMiddleware.ts, test/units/multipartfiles/middlewares/MultiparFileMiddleware.spec.ts, yarn.lock
---|---|---
****
Now @types/multer must be installed as dependencies.
=> feat(multer): Add global multer configuration.

docs/tutorials/socket-io.md, src/socketio/decorators/inputAndBroadcast.ts, src/socketio/decorators/inputAndBroadcastOthers.ts, src/socketio/decorators/inputAndEmit.ts, src/socketio/index.ts, test/units/socketio/decorators/inputAndBroadcast.spec.ts, test/units/socketio/decorators/inputAndBroadcastOthers.spec.ts, test/units/socketio/decorators/inputAndEmit.spec.ts
---|---|---
****
- Add `@InputAndEmit`
- Add `@InputAndBroadcast`
- Add `@InputAndBroadcastOthers`
=> feat(socketio): Add decorators

src/jsonschema/decorators/any.ts, test/units/jsonschema/decorators/any.spec.ts
=> fix(jsonschema): Fix Any decorator

docs/tutorials/ajv.emd, src/ajv/interfaces/IAjvSettings.ts, src/ajv/services/AjvService.ts, src/jsonschema/registries/JsonSchemesRegistry.ts, src/jsonschema/services/JsonSchemesService.ts, src/mvc/errors/ParseExpressionError.ts, test/helper/classes.ts, test/integration/ajv/ajv.spec.ts, test/units/ajv/services/AjvService.spec.ts, test/units/jsonschema/services/JsonSchemesService.spec.ts
---|---|---
Fix | Ready | Yes/No
****
Related issues: #210, #198 (error message format).
Thanks @lwallent  for your example the issue ;)
=> Fix jsonschema deep property

src/jsonschema/registries/JsonSchemesRegistry.ts, src/mvc/decorators/allow.ts, test/units/mvc/decorators/allow.spec.ts
feature(ajv): Allow(null) will create oneOf on schema with null option 
Closes #216
=> allow(null) will now write to schema.

docs/docs/converters.emd, src/ajv/services/AjvService.ts, src/converters/components/ArrayConverter.ts, src/converters/components/MapConverter.ts, src/converters/components/SetConverter.ts, src/converters/interfaces/IConverter.ts, src/converters/services/ConverterService.ts, test/integration/ajv/ajv.spec.ts, test/units/ajv/services/AjvService.spec.ts, test/units/converters/components/ArrayConverter.spec.ts, test/units/mvc/services/ValidationService.spec.ts
---|---|---
****
- QueryParams and PathParams work with Ajv,
- AjvService.validate() support collection of items.
Closes: #214
=> feat(ajv,converter): Ajv validation work with QueryParams and PathParams

src/server/components/ServerLoader.ts, test/units/server/components/ServerLoader.spec.ts
=> (fix) Fixed .ts to.js scan conversion when ts-node not available

docs/configuration.md, src/config/class/ServerSettingsProvider.ts
=> Default extension .ts

docs/docs/middlewares/override/global-error-handler.md
---|---|---
Doc | Ready | No
****
add more info when create custom error handler.
=> docs(configuration): add more info when use custom error handler.

src/swagger/decorators/title.ts, test/units/swagger/decorators/title.spec.ts
Closes: #227
---|---|---
Feature/Fix/Doc/Chore | Ready/In development/Hold | Yes/No
****
```
import {} from "ts-express-decorators";
```
=> fix(swagger): Fix error when Title decorator is used on a method

package.json, src/ajv/services/AjvService.ts, src/config/decorators/constant.ts, src/config/decorators/value.ts, src/config/index.ts, src/config/services/GlobalSerttings.ts, src/converters/errors/ConverterDeserializationError.ts, src/converters/errors/ConverterSerializationError.ts, src/di/services/InjectorService.ts, src/filters/class/FilterBuilder.ts, src/filters/errors/RequiredParamError.ts, src/jsonschema/services/JsonSchemesService.ts, src/mvc/class/HandlerBuilder.ts, src/mvc/errors/ParseExpressionError.ts, src/testing/inject.ts, test/integration/ajv/ajv.spec.ts, test/integration/app/app.ts, test/integration/rest.spec.ts, test/units/ajv/services/AjvService.spec.ts, test/units/converters/errors/ConverterDeserializationError.spec.ts, test/units/converters/errors/ConverterSerializationError.spec.ts, test/units/filters/class/FilterBuilder.spec.ts, test/units/filters/errors/RequiredParamError.spec.ts, test/units/jsonschema/decorators/uniqueItems.spec.ts, test/units/mvc/class/HandlerBuilder.spec.ts, test/units/mvc/errors/ParseExpressionError.spec.ts, test/units/socketio/decorators/socketService.spec.ts, yarn.lock
- fix cyclic dependencies on Value and Constant decorators
- fix a bug in injector when a service is override and this service is included before the original service.
- remove prepublish hook in package.json
Closes: #231
=> fix: Fix bad request error management

src/swagger/class/OpenApiParamsBuilder.ts, src/swagger/class/OpenApiPropertiesBuilder.ts, test/units/swagger/class/OpenApiParamsBuilder.spec.ts
=> fix(swagger): Fix error when BodyParams is used with an expression

docs/configuration.md, docs/fr/configuration.md, package.json, src/common/package.json, src/common/server/components/ServerLoader.ts, src/common/yarn.lock, test/units/server/components/ServerLoader.spec.ts, yarn.lock
Now ServerSettings accept an exclude patterns (`!**/*.ts`).
See configuration page.
Closes: #253
=> feat(server): Change glob to globby package.

docs/tutorials/swagger.md, package.json, readme.md, src/ajv/readme.md, src/core/readme.md, src/multipartfiles/readme.md, src/servestatic/readme.md, src/socketio/readme.md, src/swagger/class/OpenApiParamsBuilder.ts, src/swagger/decorators/hidden.ts, src/swagger/index.ts, src/swagger/readme.md, src/swagger/services/SwaggerService.ts, test/integration/app/controllers/calendars/HiddenCtrl.ts, test/integration/app/controllers/calendars/TaskCtrl.ts, test/integration/data/swagger.spec.json, test/integration/swagger.spec.ts
=> feat(swagger): Add Hidden decorator to exclude route from documentation

src/common/mvc/services/ControllerService.ts, test/units/mvc/services/ControllerService.spec.ts
=> fix(mvc): Fix router injection

docs/configuration.md, docs/docs/scope.md, docs/fr/configuration.md, src/common/config/class/ServerSettingsProvider.ts, src/common/config/decorators/constant.ts, src/common/config/decorators/value.ts, src/common/config/index.ts, src/common/config/interfaces/IServerSettings.ts, src/common/config/services/GlobalSerttings.ts, src/common/config/services/GlobalSettings.ts, src/common/di/class/ProviderStorable.ts, test/integration/app/controllers/users/UserCtrl.ts, test/integration/app/services/UserService.ts, test/integration/rest.spec.ts
- Fix scope on controller,
- Add controllerScope
Closes: #268
=> feat(mvc): Add global controllerScope configuration

docs/tutorials/socket-io.emd, docs/tutorials/upload-files-with-multer.md, src/socketio/class/SocketHandlersBuilder.ts, src/socketio/decorators/socketErr.ts, src/socketio/decorators/socketEventName.ts, src/socketio/decorators/socketMiddleware.ts, src/socketio/decorators/socketMiddlewareError.ts, src/socketio/index.ts, src/socketio/interfaces/SocketFilters.ts, test/units/socketio/class/SocketHandlersBuilder.spec.ts, test/units/socketio/decorators/socketEventName.spec.ts
- Fix documentation
- Fix exportation of SocketMiddleware and SocketMiddlewareError
Closes: #282
---|---|---
Feature/Fix/Doc/Chore | Ready/In development/Hold | Yes/No
****
```
```
=> feat(socketio): Add SocketEventName decorator

src/common/mvc/decorators/class/expressApplication.ts, src/swagger/class/OpenApiModelSchemaBuilder.ts, test/integration/app/middlewares/ThrowErrorSocketMiddleware.ts, test/integration/app/models/Event.ts, test/integration/app/services/RoomWS.ts, test/integration/data/swagger.spec.json, test/units/swagger/class/OpenApiModelSchemaBuilder.spec.ts, test/units/swagger/class/OpenApiParamsBuilder.spec.ts, test/units/swagger/class/helpers/classes.ts
=> fix(swagger): Fix swagger generation when @Any is used

docs/configuration.md, docs/contributing.md, src/common/config/class/ServerSettingsProvider.ts, src/common/config/interfaces/IServerSettings.ts, src/common/mvc/components/LogIncomingRequestMiddleware.ts, test/units/config/class/ServerSettingsProvider.spec.ts, test/units/mvc/components/LogIncomingRequestMiddleware.spec.ts
fix(log): stringify indentation is a setting on its own. 
The Indentation can be set independently on the env.
=> fix(log): stringify indentation is a setting on its own.

src/socketio/decorators/socketUseAfter.ts, src/socketio/decorators/socketUseBefore.ts
=> feat(socket): SocketUseBefore and SocketUseAfter accept multiple mdlwrs

src/socketio/services/SocketIOService.ts, test/units/socketio/services/SocketIOService.spec.ts
=> feat(socketio): Support adapter option on serverSettings level

src/socketio/class/SocketHandlersBuilder.ts, src/socketio/interfaces/ISocketHandlerMetadata.ts, src/socketio/services/SocketIOService.ts, test/integration/app/services/RoomWS.ts, test/units/socketio/class/SocketHandlersBuilder.spec.ts, test/units/socketio/services/SocketIOService.spec.ts
=> fix(socketio): Fix MaxListenersExceededWarning

docs/docs/interceptors.md, src/common/index.ts, src/common/interceptors/Intercept.ts, src/common/interceptors/Interceptor.ts, src/common/interceptors/index.ts, test/units/common/interceptors/Interceptor.spec.ts, test/units/common/interceptors/intercept.spec.ts
---|---|---
Feature | In development | No
****
Allow for interceptors to wrap service methods. Other components can be injected
```ts
import { Interceptor, IInterceptor, IInterceptorContext, Intercept, Service } from "ts-express-decorators";
@Interceptor()
class MyInterceptor implements IInterceptor {
aroundInvoke(ctx: IInterceptorContext) {
//do logic and decide if the call should proceed or not, error can be thrown as well
// ctx contains { target, method, args } as well so that the aroundInvoke can get more details
// about the method being intercepted
ctx.proceed();
}
}
@Service()
export default MyService {
@Intercept(MyInterceptor)
myMethod() {
...
}
}
```
=> Interceptors

docs/tutorials/swagger.emd, src/swagger/decorators/docs.ts, src/swagger/index.ts, src/swagger/interfaces/ISwaggerSettings.ts, src/swagger/readme.md, src/swagger/services/SwaggerService.ts, test/integration/app/app.ts, test/integration/app/controllers/calendars/HiddenCtrl.ts, test/integration/data/swagger.spec.json, test/units/swagger/services/SwaggerService.spec.ts
=> feat(swagger): Support multi swagger documentations paths

.travis.yml, docs/tutorials/swagger.emd, gulpfile.js, package.json, src/swagger/interfaces/ISwaggerSettings.ts, src/swagger/package-lock.json, src/swagger/package.json, src/swagger/readme.md, src/swagger/services/SwaggerService.ts, src/swagger/views/index.ejs, tasks/doc.js, tasks/utils/loadTasks.js, test/integration/app/spec/style.css, test/units/jsonschema/decorators/default.spec.ts, test/units/swagger/services/SwaggerService.spec.ts, yarn.lock
Replace swagger-ui-rexpress by the official npm package swagger-ui-dist
=> Feat swagger ui integration

package-lock.json, src/mongoose/utils/buildMongooseSchema.ts, test/units/mongoose/utils/buildMongooseSchema.spec.ts
=> fix(mongoose): Fix problem with the clean method

src/swagger/class/OpenApiEndpointBuilder.ts, tasks/copy.js
=> fix(build): Add tasks to copy views directories in each packages.

docs/configuration.md, docs/fr/configuration.md, src/common/config/class/ServerSettingsProvider.ts, src/common/server/components/ServerLoader.ts, src/swagger/services/SwaggerService.ts, test/units/server/components/ServerLoader.spec.ts, test/units/swagger/services/SwaggerService.spec.ts
Now, httpPort and httpsPort accept "0" as value. The server will delegate
the port assign from the OS.
Closes: #336
=> feat(server): Add random port support

src/common/jsonschema/registries/PropertyRegistry.ts
=> fix(mvc): Fix allow when Required and Allow are used at the same time

src/common/di/services/InjectorService.ts, test/integration/app/app.ts, test/integration/app/controllers/calendars/CalendarCtrl.ts, test/integration/app/middlewares/authentication.ts, test/integration/app/services/TokenService.ts
=> fix(di): Fix injector

src/common/filters/class/FilterBuilder.ts, src/common/mvc/index.ts, src/testing/loadInjector.ts
=> fix imports/exports

src/swagger/class/OpenApiEndpointBuilder.ts, src/swagger/class/OpenApiParamsBuilder.ts, src/swagger/services/SwaggerService.ts, src/swagger/utils/index.ts, test/integration/app/controllers/RestCtrl.ts, test/integration/data/swagger.spec.json, test/units/swagger/utils/index.spec.ts
=> fix(swagger): Fix pathParams swagger description

packages/swagger/views/index.ejs
=> fix(swagger): Add IE 11 support for swagger-ui

packages/swagger/interfaces/ISwaggerSettings.ts, packages/swagger/services/SwaggerService.ts, test/units/swagger/services/SwaggerService.spec.ts
=> fix(swagger): Fix default spec generation

packages/common/src/mvc/components/LogIncomingRequestMiddleware.ts, packages/common/src/mvc/index.ts
=> fix(mvc): Export LogIncomingRequestMiddleware

docs/docs/testing.md, packages/testing/src/TestContext.ts, packages/testing/src/bootstrap.ts, packages/testing/src/done.ts, packages/testing/src/index.ts, packages/testing/src/inject.ts, test/integration/di.spec.ts, test/integration/rest.spec.ts, test/integration/swagger.spec.ts, test/integration/testing-example.spec.ts, test/units/filters/services/ParseService.spec.ts, test/units/testing/TestContext.spec.ts, test/units/testing/bootstrap.spec.ts
Fixes #481 
Type | Migration
---|---
Feature | ??
See #481 
```
import {bootstrapAsPromised} from "@tsed/testing";
class TestServer extends ServerLoader {
}
beforeEach(async () => {
await bootstrapAsPromised();
});
```
=> feat(testing): Add bootstrapAsPromised

docs/tutorials/typeorm.md
---|---
Doc |  No
****
fixed typo: implement -> implements
none
none
=> Updated documentation

docs/tutorials/multer.md
Doc  | No
****
Update the documentation to better express the packages that have to be installed.
=> Updated documentation to include @tsed/multipartfiles

packages/di/src/services/InjectorService.ts
---|---
Fix | Yes/No
****
Serialization doesn't allow to pass functions to settings
=> fix(di): Remove constant serialization

docs/docs/snippets/controllers/merge-params-1.ts
=> Fix typo so the documentation can be build correctly

docs/contributing.md
=> Fix broken issue page links

packages/typeorm/package-lock.json, packages/typeorm/package.json, packages/typeorm/src/services/TypeORMService.ts
Type | Fix
****
should fix: #579
=> fix: TypeORMService (createConnection -> getConnectionManager)

packages/seq/readme.md, packages/seq/src/appenders/SeqAppender.ts
---|---
Fix | No
****
Fix problem when the log level is set as `OFF` (in `ts-log-debug`). The `bunyan` package doesn't work properly, because there is no `off` as log level in this library
=> fix(seq): fix seq off log level

docs/getting-started.md
=> Fix typo getting-started.md

docs/getting-started.md
=> chore: Update getting-started

packages/seq/src/SeqModule.ts, packages/seq/src/appenders/SeqAppender.ts, packages/seq/src/interfaces/ISeqSettings.ts
---|---
Feature | No
****
Added support of API Keys. Documentation: https://docs.datalust.co/docs/api-keys
```
import {ServerLoader, ServerSettings} from "@tsed/common";
import "@tsed/seq"; // import seq Ts.ED module
rootDir: __dirname,
seq: {
url: "http://localhost:5341",
apiKey: "GAZSFTazMQe5tuX4Pdut"
}
})
export class Server extends ServerLoader {
}
```
=> feat(seq): Add API Key support

docs/getting-started.md, packages/seq/src/SeqModule.ts, packages/seq/src/appenders/SeqAppender.ts, packages/seq/src/interfaces/ISeqSettings.ts
=> merge master

packages/seq/src/appenders/SeqAppender.ts
---|---
Fix | No
****
Remove bold wraps, as they are not shown correctly in seq.
=> fix(seq): Remove bold wraps

readme.md
Typos or bad English syntax/grammar often negatively bias a user about a project's quality (usually correctly). This is a great project, and better English will help it acquire the popularity it deserves. I'm not an English professor, but I hope you'll find this proposal useful. Cheers!
=> Linguistic improvements

docs/docs/injection-scopes.md, docs/tutorials/passport.md
Added missing types and alter wording.
---|---
Doc | No
****
* To use passport.js and it's types, we need to install `@types/passport` as a development dependency. There were also some types missing in the examples. 
* Request scope was pointing to singleton scope example code.
=> Added missing types and alter wording.

docs/snippets/getting-started/server.ts
=> docs: Update getting starting example server

docs/docs/injection-scopes.md, docs/docs/snippets/providers/scope-request.ts
---|---
Doc | No
****
Correct injection-scopes/request-scope's example snippet
For this change create "scope-request.ts" file
```
```
=> Doc : Correct injection-scopes/request-scope's example snippet

docs/configuration.md, docs/docs/middlewares/endpoint-error-middleware.md, docs/docs/middlewares/global-error-middleware.md, docs/docs/snippets/providers/getting-started-service.ts, docs/tutorials/seq.md, docs/tutorials/snippets/swagger/endpoint-documentation.ts, packages/seq/readme.md, packages/swagger/readme.md
---|---
Doc | No
****
Some docs improvements: corrections of imports, propper usage of decorators, etc.
=> Docs corrections

packages/common/src/jsonschema/decorators/const.spec.ts, packages/common/src/jsonschema/decorators/const.ts, packages/common/src/jsonschema/decorators/index.ts
---|---
Feature | No
****
Add a decorator for JSON schema [const](https://json-schema.org/understanding-json-schema/reference/generic.html#id5).
```
import { Const } from "@tsed/common";
class SignupForm {
@Const(true)
acceptsTerms: boolean;
}
```
=> feat(common): Add json schema const decorator.

docs/docs/pipes.md
=> docs: fix typos on pipes.md

docs/tutorials/ajv.md, docs/tutorials/aws.md, docs/tutorials/graphql.md, docs/tutorials/jest.md, docs/tutorials/mongoose.md, docs/tutorials/multer.md, docs/tutorials/not-found-page.md, docs/tutorials/passport.md, docs/tutorials/seq.md, docs/tutorials/serve-static-files.md, docs/tutorials/session.md, docs/tutorials/socket-io.md, docs/tutorials/swagger.md, docs/tutorials/templating.md, docs/tutorials/throw-http-exceptions.md, docs/tutorials/typeorm.md
=> docs: fix typos on guides

examples/passportjs/src/protocols/BasicProtocol.ts
---|---
Fix | No
****
Replaced $onVerify arguments decorators from @BodyParams to @Arg for username/password parameters.
=> fix(passport): Replaced @BodyParams with @Arg

docs/docs/hooks.md
=> docs: fix typo on hooks.md

docs/contributing.md
---|---
Doc | No
****
Update repo urls although redirect is present
=> docs: update repository urls on contributing doc page

docs/snippets/getting-started/server.ts
---|---
Doc | No
****
Fixed a typo in the infinitive form of verb "work" in a comment (line 22).
This will improve the documentation itself after merging my PR. No new features were added.
- [V] Documentation
=> docs: correct spelling of SERVER.ts getting-started snippet

docs/docs/providers.md
---|---
Doc | No
****
Fixed a typo in providers.md line 111.
=> docs: typo fix on providers.md

docs/tutorials/seq.md, package.json, packages/ajv/readme.md, packages/common/package.json, packages/common/readme.md, packages/common/src/jsonschema/decorators/allowTypes.ts, packages/common/src/platform/middlewares/PlatformContextMiddleware.ts, packages/core/readme.md, packages/di/readme.md, packages/exceptions/readme.md, packages/graphql/readme.md, packages/json-mapper/readme.md, packages/mongoose/readme.md, packages/multipartfiles/readme.md, packages/passport/readme.md, packages/platform-express/readme.md, packages/schema/readme.md, packages/seq/readme.md, packages/socketio/readme.md, packages/swagger/readme.md, packages/testing-mongoose/readme.md, packages/typeorm/readme.md, readme.md, yarn.lock
=> fix: Update readme

docs/configuration.md, docs/contributing.md, docs/getting-started.md
---|---
Doc | No
****
I reviewed and edited the markdown files for hacktoberfest in TypedProject/tsed/tree/production/docs
=> Fixed docs

package.json, yarn.lock
Update vue-theme-tsed to fix issue on contributors component
=> chore: Upgrade vuepress-theme-tsed version

.github/ISSUE_TEMPLATE/config.yml
=> chore: Add question and help link on issues page

packages/common/src/mvc/decorators/method/acceptMime.spec.ts, packages/common/src/mvc/decorators/method/contentType.spec.ts, packages/common/src/mvc/decorators/method/header.spec.ts, packages/common/src/mvc/decorators/params/useParam.spec.ts, packages/common/src/mvc/pipes/ValidationPipe.spec.ts, packages/common/src/platform/decorators/multer/multipartFile.spec.ts, packages/platform-test-utils/src/tests/testAuth.ts, packages/platform-test-utils/src/tests/testCtrlInheritance.ts, packages/schema/src/decorators/collections/maxProperties.spec.ts, packages/schema/src/decorators/collections/minProperties.spec.ts, packages/schema/src/decorators/common/description.spec.ts, packages/schema/src/decorators/common/name.spec.ts, packages/schema/src/decorators/operations/consumes.spec.ts, packages/schema/src/decorators/operations/deprecated.spec.ts, packages/schema/src/decorators/operations/operationId.spec.ts, packages/schema/src/decorators/operations/operationPath.spec.ts, packages/schema/src/decorators/operations/path.spec.ts, packages/schema/src/decorators/operations/produces.spec.ts, packages/schema/src/decorators/operations/returns.spec.ts, packages/schema/src/decorators/operations/security.spec.ts, packages/schema/src/decorators/operations/summary.spec.ts, packages/schema/src/decorators/operations/tags.spec.ts, packages/schema/src/domain/JsonOperation.spec.ts, packages/schema/src/utils/getSpec.spec.ts, packages/schema/src/utils/getSpec.ts, packages/schema/src/utils/mergeOperation.ts, packages/swagger/src/interfaces/SwaggerSettings.ts, packages/swagger/src/services/SwaggerService.ts, packages/swagger/test/swagger.integration.spec.ts, packages/swagger/test/swagger.query.spec.ts
---|---
Feature | No
****
Add property to enable OAS 3
=> feat(swagger): Add swagger.specVersion to switch on OAS3

CONTRIBUTING.md
=> docs: Update contribution

docs/tutorials/aws.md, docs/tutorials/snippets/aws/lambda.ts, examples/aws/package.json, examples/aws/src/LambdaServer.ts, packages/common/src/platform-builder/builder/PlatformBuilder.spec.ts, packages/common/src/platform-builder/builder/PlatformBuilder.ts, packages/di/src/services/DIConfiguration.ts, packages/platform-aws/.npmignore, packages/platform-aws/package.json, packages/platform-aws/readme.md, packages/platform-aws/src/components/PlatformAws.spec.ts, packages/platform-aws/src/components/PlatformAws.ts, packages/platform-aws/src/constants/index.ts, packages/platform-aws/src/decorators/awsContext.spec.ts, packages/platform-aws/src/decorators/awsContext.ts, packages/platform-aws/src/decorators/awsEvent.spec.ts, packages/platform-aws/src/decorators/awsEvent.ts, packages/platform-aws/src/index.ts, packages/platform-aws/src/pipes/ParseApiGatewayPipe.spec.ts, packages/platform-aws/src/pipes/ParseApiGatewayPipe.ts, packages/platform-aws/test/app/Server.ts, packages/platform-aws/test/app/controllers/AwsCtrl.ts, packages/platform-aws/test/aws.integration.spec.ts, packages/platform-aws/tsconfig.compile.json, packages/platform-express/readme.md, packages/platform-express/src/index.ts, packages/platform-koa/src/index.ts, packages/swagger/test/swagger.integration.spec.ts, yarn.lock
---|---
Feature | No
****
A package to configure Ts.ED with AWS
Create a new `LambdaServer.ts` in `src` directory:
```typescript
import {PlatformAws} from "@tsed/platform-aws";
import "@tsed/platform-express" 
// or import "@tsed/platform-koa"
PlatformAws.bootstrap(Server, {
aws: {
binaryMimeTypes: [ // optional
// mime types list 
]
},
// additional Ts.ED options. See https://tsed.io/tutorials/aws.html
});
// Handler used by AWS
export const handler = PlatformAws.callback();
```
Then create `lambda.js` on your root project:
```javascript
module.exports = require("./dist/LambdaServer.js");
```
This file will be used by AWS to forward request to your application.
Finally, [package and create your Lambda function](http://docs.aws.amazon.com/lambda/latest/dg/nodejs-crea …
=> feat(aws): Add new package @tsed/platform-aws

packages/platform-express/src/components/PlatformExpress.ts, packages/swagger/src/interfaces/SwaggerSettings.ts, packages/swagger/test/app/Server.ts, packages/swagger/test/swagger.errors.spec.ts, packages/swagger/test/swagger.integration.spec.ts, packages/swagger/test/swagger.query.spec.ts
Fix issue on PlatformExpress module and fix swagger settings interface declaration.
=> Fix minor issues

packages/swagger/src/class/OpenApiModelSchemaBuilder.ts, packages/swagger/src/class/OpenApiParamsBuilder.spec.ts, packages/swagger/test/swagger.integration.spec.ts
---|---
Fix |No
****
Also, add tests to ensure these mistakes won't happen
Closes #921
=> fix(swagger): remove the generation of useless builtin types

docs/contributing.md
---|---
Doc| No
****
The ellipsis doesn't end a sentence. A dot does.
=> Fix some typos, mostly missing dots.

CONTRIBUTING.md
=> docs: change mail contact to gitter community

CODE_OF_CONDUCT.md
=> docs: Create_Code_of_Conduct 

packages/core/src/utils/getValue.spec.ts, packages/core/src/utils/getValue.ts, packages/core/src/utils/uniq.ts
=> Improve core

stale.yml
=> docs: create stale.yml

docs/docs/serve-files.md, docs/docs/templating.md, docs/docs/upload-files.md, docs/tutorials/socket-io.md, docs/tutorials/typeorm.md
=> Rc fix doc typos

docs/.vuepress/config.js, package.json, yarn.lock
Update tsed theme version to v3
=> Fix tsed theme

docs/.vuepress/config.js
=> docs: Add Logger url

docs/docs/exceptions.md
=> Fix typos in exceptions.md

docs/docs/snippets/authentication/auth-decorator-example-2.ts
=> docs: Update documentation about Auth

packages/common/src/platform-builder/builder/PlatformBuilder.spec.ts, packages/common/src/platform-builder/builder/PlatformBuilder.ts
=> fix(common): Add PlatformBuilder.close method to stop gracefully the server

packages/swagger/src/services/SwaggerService.ts, packages/swagger/test/swagger.children.spec.ts, packages/swagger/test/swagger.integration.spec.ts
Closes: #1029
```typescript
import {Controller, Get, PlatformTest} from "@tsed/common";
import {PlatformExpress} from "@tsed/platform-express";
import {expect} from "chai";
import * as SuperTest from "supertest";
import {Server} from "./app/Server";
@Controller("/:campaignID/polls")
export class PollCtrl {
@Get("/:pollId")
get() {
}
}
@Controller({path: "/:orgName/campaigns", children: [PollCtrl]})
export class CampaignCtrl {
}
@Controller({
path: "/orgs",
children: [CampaignCtrl]
})
export class OrgCtrl {
}
describe("Swagger integration", () => {
describe("OpenSpec2", () => {
let request: SuperTest.SuperTest<SuperTest.Test>;
beforeEach(
PlatformTest.bootstrap(Server, {
platform: PlatformExpress,
mount: {
"/api/v1": [OrgCtrl]
}
})
);
beforeEach(() => {
request = …
```
=> fix(swagger): Fix children path generation on swagger spec

packages/common/src/index.ts, packages/common/src/platform-response-filter/index.ts
---|---
Fix| No
****
Adds missing barrel file for Platform Response Filter for #1034
=> fix(common): Add missing barrel file for response filter

.github/workflows/build.yml, docs/.vuepress/config.js, docs/.vuepress/enhanceApp.js, packages/multipartfiles/src/decorators/multipartFile.spec.ts, packages/multipartfiles/src/decorators/multipartFile.ts, packages/multipartfiles/test/helpers/controllers/ArchiveController.ts, packages/multipartfiles/test/integration.spec.ts
=> fix(#1046): Required works now with multipartFile

packages/common/src/platform/decorators/multer/multipartFile.ts, packages/platform-test-utils/src/tests/testMulter.ts
=> fix(#1046): Required decorator works now with multipartFile

packages/common/src/platform-builder/utils/getConfiguration.spec.ts, packages/common/src/platform-builder/utils/getConfiguration.ts
=> fix(#1058): Fix typo on configuration building for componentsScan

packages/di/src/services/InjectorService.ts, packages/di/test/integration/async-factory.spec.ts
=> fix(di): Fix asyncFactory when the bean is injected with @Inject on server

.nycrc, packages/json-mapper/src/utils/serialize.ts, packages/json-mapper/test/integration/models.integration.spec.ts
=> fix(json-mapper): Fix issue on json-mapper when the used decorator is wrong

packages/schema/src/utils/mergeSpec.ts, yarn.lock
Type | Breaking Change
---|---
Fix | No
****
Fix mergeSpec not deduping tags (bug #1076)
=> Fix mergeSpec duplicate tags

packages/schema/src/decorators/common/const.spec.ts, packages/schema/src/utils/serializeJsonSchema.ts
=> fix(schema): Remove unsupported const from OPENSPEC

packages/ajv/readme.md, packages/common/readme.md, packages/core/readme.md, packages/di/readme.md, packages/exceptions/readme.md, packages/graphql/readme.md, packages/json-mapper/readme.md, packages/mongoose/readme.md, packages/openspec/readme.md, packages/passport/readme.md, packages/platform-aws/readme.md, packages/platform-express/readme.md, packages/platform-koa/readme.md, packages/schema/readme.md, packages/seq/readme.md, packages/socketio/readme.md, packages/swagger/readme.md, packages/testing-mongoose/readme.md, packages/typeorm/readme.md
=> chore: Update readme

packages/openspec/src/openspec3/OS3Flows.ts, packages/openspec/src/openspec3/OS3Security.ts
---|---
Fix | No
****
Fix oauth2 flow not properly handling scopes in tsed/openspec
=> fix(openspec): Fix OAuth2 scopes in OS3

packages/common/src/platform/decorators/multer/multipartFile.spec.ts, packages/common/src/platform/decorators/multer/multipartFile.ts, packages/schema/src/domain/JsonOperation.ts, packages/schema/src/domain/JsonParameter.ts, packages/schema/src/domain/JsonParameterTypes.ts, packages/schema/src/utils/getJsonType.spec.ts, packages/schema/src/utils/getJsonType.ts
---|---
Fix | No
****
This commit tries to reintroduce file support. I'm not sure if this is the best way to do this, so please let me know if you'd like anything changed.
=> fix(schema): Added file upload support

packages/common/src/platform/decorators/multer/multipartFile.spec.ts, packages/platform-test-utils/src/tests/testAuth.ts, packages/schema/src/decorators/operations/returns.spec.ts, packages/schema/src/decorators/operations/returns.ts, packages/schema/src/decorators/operations/status.spec.ts, packages/schema/src/domain/JsonResponse.ts, packages/schema/src/utils/serializeJsonSchema.ts, packages/schema/src/utils/toJsonMapCollection.ts
Closes: #1083
---|---
Feature | No
=> feat(schema): Add Returns.Title chained decorator

docs/docs/templating.md
=> docs: consolidate Template Engine Instances

packages/json-mapper/src/utils/serialize.ts, packages/json-mapper/test/integration/models.date.intregration.spec.ts
=> fix(json-mapper): Fix issue when using OnSerialize with Date meta type

docs/getting-started/migration-from-v5.md
=> docs: Fix typos and remove unexisting link

docs/tutorials/objection.md, packages/objection/.npmignore, packages/objection/package.json, packages/objection/src/decorators/Entity.ts, packages/objection/src/decorators/IdColumn.ts, packages/objection/src/index.ts, packages/objection/src/utils/connect.ts, packages/objection/test/helpers/Server.ts, packages/objection/test/helpers/connections/ConnectionProvider.ts, packages/objection/test/helpers/migrations/01_users.ts, packages/objection/test/helpers/models/User.ts, packages/objection/test/helpers/seeds/01_users.ts, packages/objection/test/integration.spec.ts, packages/objection/tsconfig.compile.json
I started working on a @tsed/objection plugin to integrate [Objection.js](https://vincit.github.io/objection.js/) into Ts.ED.
Currently it's just very basic functionality based on the gist (https://gist.github.com/Romakita/32da7db47264f29bb535c6546459de9d)
A few questions:
- What functionality do I need to add to integrate it into Ts.ED the correct way (think services, providers etc)?
- Knex depends on database connection packages (pg, sqlite, mysql etc) which are not installed by default. Because the database connection is created inside the plugin, installing them into the main project does not work. How should I provide support for all databases without actually installing all the required packages?
- Currently the `Model` class is re-exported inside the plugin to make sure the same …
=> Objection.js plugin (WIP)

docs/docs/platform-api.md
=> docs: fix typos in platform api doc

docs/docs/platform-api.md
=> docs: Update migration guide and platform api doc

packages/json-mapper/src/utils/serialize.spec.ts, packages/json-mapper/src/utils/serialize.ts, packages/platform-test-utils/src/tests/testResponse.ts
=> fix(json-mapper): Fix issue raw class serialization

packages/ajv/src/decorators/useSchema.ts, packages/common/src/jsonschema/decorators/schema.ts, packages/schema/src/decorators/common/schema.ts, packages/schema/src/utils/getRequiredProperties.ts
Related: #1100
---|---
Fix | No
=> fix(schema): Fix issue on getRequiredProperties

docs/docs/upload-files.md, docs/getting-started/migration-from-v5.md, packages/common/src/config/interfaces/PlatformMulterSettings.ts, packages/common/src/mvc/decorators/method/returnType.ts, packages/schema/src/decorators/operations/returns.spec.ts, packages/schema/src/decorators/operations/returns.ts
=> Fix minor typings issue

packages/common/src/platform/middlewares/PlatformMulterMiddleware.spec.ts, packages/common/src/platform/middlewares/PlatformMulterMiddleware.ts
=> fix(common): Fix MulterOption decorator mapping

.gitignore, packages/platform-express/test/pageable.spec.ts, packages/schema/src/domain/JsonParameter.ts, packages/schema/src/utils/serializeJsonSchema.ts, packages/schema/test/nullable.integration.spec.ts, packages/schema/test/pageable.integration.spec.ts
=> fix(schema): Fix OS3 description on QueryParams and nullable options

packages/schema/src/decorators/operations/returns.spec.ts, packages/schema/src/decorators/operations/returns.ts, packages/schema/src/decorators/operations/status.spec.ts, packages/schema/src/domain/JsonResponse.ts
=> fix(schema): Fix examples spec generation for OpenSpec 3

docs/getting-started/start-from-scratch.md, packages/mongoose/package.json, packages/mongoose/src/interfaces/MongooseModel.ts, packages/platform-express/package.json, yarn.lock
See https://github.com/Automattic/mongoose/issues/9684
=> fix(mongoose): Fix issue about mongoose v5.11.5

packages/common/src/platform/domain/PlatformContext.ts, packages/common/src/platform/services/PlatformHandler.ts, packages/passport/src/services/ProtocolsService.ts
=> feat: Add createCustomHandler to PlatformHandler.ts

docs/docs/model.md, docs/getting-started/README.md, docs/getting-started/migration-from-v5.md, docs/tutorials/ajv.md, packages/ajv/src/decorators/keyword.ts, packages/ajv/src/interfaces/KeywordMethods.ts, packages/ajv/src/pipes/AjvValidationPipe.ts, packages/ajv/src/services/Ajv.ts, packages/ajv/test/integration/keywords.integration.spec.ts, packages/schema/src/interfaces/JsonSchemaOptions.ts
=> Feat ajv keywords

docs/tutorials/mongoose.md, docs/tutorials/snippets/mongoose/testing-api.mocha.ts, packages/testing-mongoose/readme.md
---|---
Doc | No
****
Updating testing-mongoose doc
=> docs(testing-mongoose): Updating testing API docs for mongoose

packages/json-mapper/src/utils/deserialize.ts, packages/mongoose/src/decorators/model.ts, packages/mongoose/src/decorators/ref.spec.ts, packages/mongoose/src/decorators/ref.ts, packages/mongoose/src/decorators/virtualRef.spec.ts, packages/mongoose/src/registries/MongooseModels.ts, packages/mongoose/src/utils/createSchema.spec.ts, packages/mongoose/src/utils/createSchema.ts, packages/mongoose/test/helpers/models/User.ts, packages/mongoose/test/ref.integration.spec.ts, packages/mongoose/test/resources.integration.spec.ts, packages/testing-mongoose/package.json
---|---
Fix | No
****
Fix Ref decorator and support collection.
=> Fix mongoose ref

packages/schema/src/decorators/common/groups.spec.ts, packages/schema/src/utils/getRequiredProperties.ts, packages/schema/src/utils/serializeJsonSchema.ts
=> fix(schema): Fix validation issue when Required decorator is used with Groups

packages/json-mapper/src/components/DateMapper.ts, packages/mongoose/src/interfaces/MongooseModel.ts, packages/mongoose/src/utils/createSchema.ts, packages/mongoose/test/helpers/models/User.ts, packages/mongoose/test/ref.integration.spec.ts, packages/mongoose/test/resources.integration.spec.ts, packages/schema/src/decorators/common/ignore.ts
---|---
Fix | No
****
Fix the following issue:
```
TypeError: object.toISOString is not a function
at DateMapper.serialize
```
=> fix(mongoose): Fix the serialization and the problem with Date

packages/mongoose/src/decorators/ref.ts
=> fix(mongoose): Fix ref decorator when the ref is undefined

packages/ajv/src/index.ts
---|---
Fix | No
****
Exported Keyword and KeywordMethods on ajv domain
Closes: #1161
=> fix(ajv): Add missing keyword exports

packages/common/src/platform-builder/builder/PlatformBuilder.ts, packages/common/src/platform/services/PlatformApplication.spec.ts, packages/common/src/platform/services/PlatformApplication.ts, packages/platform-express/src/components/PlatformExpress.ts, packages/platform-express/src/services/PlatformExpressApplication.ts, packages/platform-express/test/app/Server.ts, packages/platform-express/test/app/index.ts, packages/platform-koa/src/components/PlatformKoa.ts, packages/platform-koa/src/services/PlatformKoaApplication.ts
=> fix(platform): Add app router after $onInit/$afterInit hook to allow express query string configuration

packages/oidc-provider/src/index.ts
=> fix(oidc): Add missing import on oidc-provider module

docs/tutorials/oidc.md, packages/common/src/platform-builder/builder/PlatformBuilder.ts, packages/di/src/class/LocalsContainer.spec.ts, packages/di/src/class/LocalsContainer.ts, packages/json-mapper/src/decorators/onDeserialize.ts, packages/json-mapper/src/decorators/onSerialize.ts, packages/json-mapper/src/utils/deserialize.spec.ts, packages/oidc-provider/src/domain/OidcClientsMethods.ts, packages/oidc-provider/src/domain/OidcSettings.ts, packages/oidc-provider/src/domain/index.ts, packages/oidc-provider/src/services/OidcProvider.spec.ts, packages/oidc-provider/src/services/OidcProvider.ts
---|---
Fix | No (yes for alpha package @tsed/oidc-provider)
=> Fix 1157 oidc clients

docs/.vuepress/config.js, docs/release.md, packages/common/src/mvc/decorators/method/status.spec.ts, packages/schema/src/domain/JsonOperation.ts, packages/schema/src/domain/JsonResponse.ts, packages/schema/src/utils/getSpec.spec.ts, packages/schema/test/response.integration.spec.ts
Closes: #1175
---|---
Fix | No
****
=> fix(schema): Fix swagger schema when 204 status is used

packages/adapters-redis/.npmignore, packages/adapters-redis/package.json, packages/adapters-redis/readme.md, packages/adapters-redis/src/adapters/RedisAdapter.spec.ts, packages/adapters-redis/src/adapters/RedisAdapter.ts, packages/adapters-redis/src/domain/RedisAdaptersSettings.ts, packages/adapters-redis/src/index.ts, packages/adapters-redis/src/services/RedisFactory.ts, packages/adapters-redis/tsconfig.compile.json, packages/adapters/src/adapters/FileSyncAdapter.spec.ts, packages/adapters/src/adapters/FileSyncAdapter.ts, packages/adapters/src/adapters/LowDbAdapter.ts, packages/adapters/src/adapters/MemoryAdapter.spec.ts, packages/adapters/src/decorators/indexed.spec.ts, packages/adapters/src/decorators/indexed.ts, packages/adapters/src/decorators/injectAdapter.spec.ts, packages/adapters/src/decorators/injectAdapter.ts, packages/adapters/src/domain/Adapter.ts, packages/adapters/src/domain/AdaptersSettings.ts, packages/adapters/src/index.ts, packages/adapters/src/services/Adapters.ts, packages/oidc-provider/src/services/OidcAdapters.ts, yarn.lock
=> Feat adapter redis

packages/schema/src/utils/getJsonPathParameters.spec.ts, packages/schema/src/utils/getJsonPathParameters.ts, packages/schema/test/dynamicurl.integration.spec.ts
Closes: #1190
---|---
Fix | No
=> fix(schema): Generate correctly OpenSpec when url is /JQ=:id

docs/docs/controllers.md, docs/docs/snippets/controllers/params-decorator.ts, docs/docs/snippets/controllers/params-post-any.ts, docs/docs/snippets/controllers/params-post-array-with-model.ts, docs/docs/snippets/controllers/params-post-array.ts, docs/docs/snippets/controllers/params-post-inline-validation.ts, docs/docs/snippets/controllers/params-post-string.ts, docs/getting-started/migration-from-v5.md, packages/platform-express/test/array-body.spec.ts, packages/platform-test-utils/src/tests/testBodyParams.ts, packages/schema/src/utils/getSpec.spec.ts
Closes: #1190
---|---
Fix | No
=> docs(#1186): Add migration details on `any` type used with BodyParams

packages/common/src/platform/builder/PlatformControllerBuilder.ts, packages/common/src/platform/decorators/multer/multipartFile.ts
Closes: #1189
---|---
Fix | No
=> fix(common): Fix issue when using passport and multer on route

packages/common/src/platform/middlewares/PlatformAcceptMimesMiddleware.spec.ts, packages/common/src/platform/middlewares/PlatformAcceptMimesMiddleware.ts
Closes: #1196
---|---
Fix | No
****
=> fix(common): Improve PlatformAcceptMimesMiddleware to allow usage without endpoint

packages/common/src/platform/services/PlatformResponse.spec.ts, packages/common/src/platform/services/PlatformResponse.ts, packages/platform-express/test/app/index.ts, packages/platform-express/test/app/public/index.html, packages/platform-test-utils/src/tests/testResponse.ts
=> chore(common): Fix returned buffer from method

packages/schema/src/decorators/common/hidden.ts, packages/schema/src/decorators/index.ts, packages/schema/src/utils/getSpec.ts, packages/swagger/test/app/class/classes.ts, packages/swagger/test/app/index.ts, packages/swagger/test/swagger.integration.spec.ts
=> fix(schema,swagger): Fix regression on Hidden decorator introduce with v6

packages/common/src/platform-builder/interfaces/OnRequest.ts
=> fix(common): Fix OnRequest interface

packages/common/src/platform-builder/builder/PlatformBuilder.ts, packages/common/src/platform/services/PlatformHandler.ts, packages/common/src/platform/services/PlatformRequest.spec.ts, packages/common/src/platform/services/PlatformRequest.ts, packages/di/src/class/LocalsContainer.spec.ts, packages/di/src/class/LocalsContainer.ts, packages/di/src/services/DITest.ts, packages/oidc-provider/test/oidc.integration.spec.ts, packages/platform-express/test/platform-express.spec.ts, packages/platform-koa/src/services/PlatformKoaHandler.ts, packages/platform-koa/src/services/PlatformKoaRequest.spec.ts, packages/platform-koa/src/services/PlatformKoaRequest.ts, packages/platform-test-utils/src/tests/testHeaders.ts, packages/stripe/test/stripe.integration.spec.ts, packages/swagger/src/SwaggerModule.ts, packages/swagger/src/interfaces/SwaggerSettings.ts, test/helper/logger.ts
=> Feat add hooks

packages/ajv/src/services/AjvService.ts, packages/platform-express/src/components/PlatformExpress.ts, packages/platform-express/src/middlewares/rawBodyMiddleware.ts, packages/platform-express/test/app/Server.ts, packages/platform-test-utils/src/tests/testBodyParams.ts, packages/platform-test-utils/src/tests/testMulter.ts
=> chore(common): Add complementary unit test

docs/tutorials/snippets/graphql/server-configuration.ts
---|---
Doc | No
****
Fix string interpolation on graphql server configuration snippets.
=> docs: fix string interpolation

packages/swagger/src/SwaggerModule.ts
=> fix(swagger): Use normalize path instead of resolve to solve issue on  windows

.github/workflows/build.yml, packages/common/src/platform-builder/builder/PlatformBuilder.spec.ts, packages/openspec/src/openspec3/OS3Security.ts
=> Fix os3 oidc

packages/common/test/integration/returns.spec.integration.ts, packages/platform-express/test/plainText.spec.ts, packages/platform-express/test/response-filter.spec.ts, packages/platform-test-utils/src/tests/testResponse.ts, packages/schema/src/decorators/operations/returns.spec.ts, packages/schema/src/domain/JsonEntityStore.ts, packages/schema/src/domain/JsonResponse.ts
=> fix(common): Fix response filter when plain/text

.github/workflows/build.yml
=> chore: Update github action matrix

.github/workflows/build.yml
=> chore: Increase the timeout

docs/docs/converters.md, packages/json-mapper/src/components/DateMapper.spec.ts, packages/json-mapper/src/components/DateMapper.ts
Closes: #1231
---|---
****
```typescript
```
=> fix(json-mapper): Fix mixed type deserialization on DateMapper

packages/schema/src/decorators/common/customKey.spec.ts, packages/schema/src/decorators/common/customKey.ts
=> fix(schema): Add @CustomKeys

docs/tutorials/snippets/swagger/configuration.ts
---|---
Doc | No
****
Fixed invalid swagger config version 2.0.0. value in docs
=> fixed invalid swagger config version 2.0.0. value in docs

docs/docs/request-context.md, docs/release.md, packages/async-hook-context/.npmignore, packages/async-hook-context/package.json, packages/async-hook-context/readme.md, packages/async-hook-context/src/decorators/injectContext.ts, packages/async-hook-context/src/index.ts, packages/async-hook-context/src/services/PlatformAsyncHookContext.ts, packages/async-hook-context/test/app/Server.ts, packages/async-hook-context/test/async-hook-context.integration.ts, packages/async-hook-context/tsconfig.compile.json, packages/common/src/platform/services/PlatformHandler.ts, packages/di/src/decorators/inject.spec.ts, packages/di/src/decorators/inject.ts, packages/di/src/interfaces/IInjectableProperties.ts, packages/di/src/services/InjectorService.ts
=> Feat 1134 async hooks context

docs/tutorials/mongoose.md, docs/tutorials/snippets/mongoose/extended-circular-reference.ts
---|---
****
```typescript
```
=> Mongoose Circular Reference Doc update

packages/graphql/package.json, packages/graphql/src/GraphQLModule.ts, packages/graphql/src/interfaces/GraphQLSettings.ts, packages/graphql/test/app/Server.ts, packages/graphql/test/app/graphql/auth/AuthResolver.ts, packages/graphql/test/app/graphql/auth/User.ts, packages/graphql/test/app/index.ts, packages/graphql/test/app/protocols/GraphQLProtocol.ts, packages/graphql/test/app/services/UsersRepository.ts, packages/graphql/test/graphql-passport.spec.ts, yarn.lock
=> fix(graphql): Fix graphql registration order

docs/.vuepress/config.js, package.json, yarn.lock
---|---
Doc | No
****
```typescript
```
=> docs: Update website configuration

docs/docs/cache.md, packages/common/src/platform-cache/interceptors/PlatformCacheInterceptor.ts, packages/common/src/platform-cache/services/PlatformCache.ts, packages/platform-test-utils/src/tests/testCache.ts
---|---
****
```typescript
```
=> fix(common): Fix `cache: false` option and optimize perf

docs/docs/cache.md
---|---
****
```typescript
```
=> Fix typos on cache.md

packages/common/src/platform-cache/interceptors/PlatformCacheInterceptor.ts, packages/common/src/platform-cache/interfaces/PlatformCacheOptions.ts, packages/common/src/platform-cache/services/PlatformCache.ts
=> feat(common): UseCache support serialization/deserialization

packages/common/src/platform-cache/interceptors/PlatformCacheInterceptor.ts, packages/mongoose/src/MongooseModule.ts, packages/mongoose/src/services/MongooseService.ts
---|---
****
```typescript
```
=> Chore refactoring cache

docs/docs/logger.md, docs/tutorials/seq.md, package.json, packages/common/package.json, packages/common/src/config/interfaces/PlatformLoggerSettings.ts, packages/common/src/platform/builder/PlatformBuilder.ts, packages/common/src/platform/utils/callHook.ts, packages/seq/package.json, packages/seq/src/SeqModule.ts, yarn.lock
---|---
****
```typescript
```
=> Fix 1279 seq configuration

docs/docs/model.md, packages/common/src/mvc/decorators/allow.spec.ts, packages/common/src/mvc/decorators/required.spec.ts, packages/common/src/platform-exceptions/domain/ExceptionSchema.spec.ts, packages/common/src/platform/decorators/multer/multipartFile.spec.ts, packages/platform-test-utils/src/tests/testAuth.ts, packages/schema/src/decorators/common/allow.ts, packages/schema/src/decorators/common/groups.spec.ts, packages/schema/src/decorators/common/groups.ts, packages/schema/src/decorators/common/requiredGroups.spec.ts, packages/schema/src/decorators/common/requiredGroups.ts, packages/schema/src/decorators/operations/returns.spec.ts, packages/schema/src/decorators/operations/status.spec.ts, packages/schema/src/domain/JsonSchema.spec.ts, packages/schema/src/domain/JsonSchema.ts, packages/schema/src/hooks/alterRequiredGroups.ts, packages/schema/src/utils/from.spec.ts, packages/schema/src/utils/getRequiredProperties.ts, packages/schema/src/utils/matchGroups.ts, packages/schema/src/utils/serializeJsonSchema.ts
=> Feat 1200 required groups

packages/mongoose/src/decorators/indexed.ts, packages/mongoose/src/utils/createSchema.ts
---|---
****
```typescript
```
=> fix(mongoose): Fix Indexed signature decorator

package.json, packages/adapters/package.json, packages/ajv/package.json, packages/async-hook-context/package.json, packages/common/package.json, packages/core/package.json, packages/di/package.json, packages/exceptions/package.json, packages/formio/package.json, packages/graphql/package.json, packages/json-mapper/package.json, packages/mongoose/package.json, packages/objection/package.json, packages/oidc-provider/package.json, packages/passport/package.json, packages/schema/package.json, packages/seq/package.json, packages/socketio/package.json, packages/stripe/package.json, packages/swagger/package.json, packages/testing-mongoose/package.json, packages/typeorm/package.json, yarn.lock
=> fix: Update dependencies

packages/common/src/mvc/interfaces/ResponseErrorObject.ts, packages/common/src/platform-exceptions/components/ErrorFilter.spec.ts, packages/common/src/platform-exceptions/components/ErrorFilter.ts
---|---
****
```typescript
```
=> fix(common): ResponseErrorObject.errors can be an object

docs/.vuepress/config.js, docs/package.json, docs/warehouse/README.md, docs/yarn.lock
---|---
****
```typescript
```
=> docs: Add Warehouse page

packages/formio/src/FormioModule.ts, packages/formio/src/components/AlterActions.ts, packages/formio/src/domain/FormioAuth.ts, packages/formio/src/domain/FormioDecodedToken.ts, packages/formio/src/domain/FormioHooks.ts, packages/formio/src/index.ts, packages/formio/src/services/FormioAuthService.spec.ts, packages/formio/src/services/FormioAuthService.ts, packages/formio/src/services/FormioDatabase.spec.ts, packages/formio/src/services/FormioDatabase.ts, packages/formio/src/services/FormioHooksService.spec.ts, packages/formio/src/services/FormioHooksService.ts, packages/formio/src/services/FormioService.spec.ts, packages/formio/src/services/FormioService.ts, packages/formio/src/utils/isMongoId.ts, packages/mongoose/src/MongooseModule.ts, packages/passport/src/decorators/protocol.ts, packages/passport/src/interfaces/ProtocolOptions.ts, packages/passport/src/interfaces/index.ts, packages/passport/src/middlewares/PassportMiddleware.spec.ts, packages/passport/src/middlewares/PassportMiddleware.ts, packages/passport/src/services/ProtocolsService.ts
=> Feat formio auth

docs/.vuepress/config.js, docs/tutorials/keycloak.md
---|---
Doc | No
****
Adds documentation to integrate Keycloak into an existing Ts.ED project.
=> docs: Add Keycloak documentation

packages/ajv/package.json
---|---
Feature | No
****
Just an update to support AJV 8 (and keep support for 7).
=> Update AJV dev+peerDependency

packages/di/src/services/InjectorService.spec.ts, packages/di/src/services/InjectorService.ts
=> fix(di): Allow falsy value when creating a useValue provider

docs/docs/model.md, packages/json-mapper/src/decorators/afterDeserialize.ts, packages/json-mapper/src/decorators/beforeDeserialize.ts, packages/json-mapper/src/hooks/alterAfterDeserialize.ts, packages/json-mapper/src/hooks/alterBeforeDeserialize.ts, packages/json-mapper/src/utils/deserialize.ts, packages/json-mapper/test/helpers/FoodStatus.ts, packages/json-mapper/test/integration/after.deserialize.integration.spec.ts, packages/json-mapper/test/integration/before.deserialize.integration.spec.ts, packages/json-mapper/test/integration/custom.validation.decorator.ts
---|---
Feature | No
****
Closes #1336.
=> feat(before-deserialize-decorator): Add BeforeDeserialize decorator

team.json
---|---
Doc | No
****
I want to support and improve tsed :).
=> docs(team): Add to team

packages/openspec/src/openspec3/index.ts, packages/schema/src/decorators/operations/returns.ts
=> fix(openspec,common): Fix wrong import of OS3Example

docs/docs/model.md, packages/schema/src/decorators/common/forwardGroups.spec.ts, packages/schema/src/decorators/common/forwardGroups.ts, packages/schema/src/decorators/common/groups.ts, packages/schema/src/domain/JsonSchema.ts, packages/schema/src/utils/serializeJsonSchema.ts
=> feat(schema): Add @ForwardGroups decorator

packages/formio/src/services/FormioAuthService.spec.ts, packages/formio/src/services/FormioAuthService.ts
---|---
****
```typescript
```
=> feat(formio): Add FormioAuthService.updateSubmissionRole

packages/objection/readme.md
---|---
Fix/Doc | No
****
```typescript
```
=> fix: packages/objection/readme.md

package.json, packages/common/src/platform/domain/HandlerContext.ts, packages/platform-test-utils/src/tests/testResponse.ts, yarn.lock
=> chore: Add unit test to cover axios usecase

packages/formio/src/domain/FormioModels.ts, packages/formio/src/services/FormioAuthService.spec.ts, packages/formio/src/services/FormioAuthService.ts
=> fix(formio): Update typings and rename unused method

packages/formio/src/services/FormioAuthService.spec.ts, packages/formio/src/services/FormioAuthService.ts
---|---
****
```typescript
```
=> fix(formio): Change the returned result object for updateUser method

.github/workflows/build.yml, packages/di/src/interfaces/IInjectableProperties.ts, packages/di/src/services/InjectorService.ts
---|---
Feature | No
****
Added ability to define `onGet` injectable property option
=> feat: Added ability to override injectable property getter

packages/common/src/platform/services/PlatformHandler.ts
---|---
Feature | No
****
Added ability to hack `onRequest` handler.
Could be useful for context defining.
=> feat: added ability to customize request handler

packages/common/src/mvc/models/HandlerMetadata.spec.ts, packages/common/src/mvc/models/HandlerMetadata.ts, packages/common/src/platform/services/PlatformHandler.ts
ref: #1384
---|---
****
```typescript
```
=> fix(common): Prevent bad context when request is done

packages/schema/src/decorators/common/additionalProperties.ts, packages/schema/src/decorators/common/allOf.spec.ts, packages/schema/src/decorators/common/allOf.ts, packages/schema/src/decorators/common/anyOf.spec.ts, packages/schema/src/decorators/common/anyOf.ts, packages/schema/src/decorators/common/oneOf.spec.ts, packages/schema/src/decorators/common/oneOf.ts, packages/schema/src/decorators/operations/in.ts, packages/schema/src/domain/JsonSchema.ts, packages/schema/src/utils/from.ts, packages/schema/src/utils/mapToJsonSchema.ts, packages/schema/src/utils/serializeJsonSchema.ts
Closes: #1383
---|---
****
```typescript
```
=> fix(schema): Allow usage of class with OneOf, AllOf and AnyOf decorator

packages/schema/src/domain/JsonOperation.ts, packages/swagger/test/swagger.bodyparams.spec.ts
=> fix(schema): Fix BodyParams generation when expression is used without other decorator to declare schema

docs/tutorials/mongoose.md
=> doc: Update path issue
