tsedio/tsed

src/controllers/controller.ts

Thanks for the great project. It helps a lot.
I found an issue when I use tsc compiler compile to target es6, the controller doesn't work.
So I dig in the source code, I found that when compile to es6, the controller class doesn't convert to function style, then the `Object.keys(this.targetClass.prototype)` always return blank array `[]`.
for example
```
// compiler target es6 
class UsersController { 
constructor(templateService, calendarsServer) {
this.templateService = templateService;
this.calendarsServer = calendarsServer;
}
indexAction(request, response) {
}
get index() {
}
};
// compiler target es5
function UsersController1(templateService, calendarsServer) {
this.templateService = templateService;
this.calendarsServer = calendarsServer;
}
UsersController1.prototype.indexAction = …
```

fix tsconfig.json build target es6 not working issue

---

src/decorators/authenticated.ts
src/interfaces/Express.d.ts
test/helper/controllers/calendars/CalendarCtrl.ts

This would enable autorisation based on a autorisation config object passed in `@Autentication()` decorator.
Example `@Authenticated({role: "admin"})`

Proposal for autorisation config

---

readme.md

Parameter for the method `.createHttpServer()` is passed directly to Http Instance. People should be aware that binding interface can be passed here.

Increase awareness for binding interface

---

src/controllers/endpoint.ts

Let the user send data "by hand". If headers are already send probably
the user used `response.send(data)`. We should not try to send it or we
will get a 'Headers already sent' error.

Do not send data if headers already sent

---

src/server/server-loader.ts

Allow create server on specific interface ex: `server.createHttpServer('127.0.0.1:49080')`
Http.listen is not expanding by default `hostname:port`. It has a first parameter string but is the path for a local socket connection. If we want to pass a local interface we should call `Http.listen(port, interface)`

Pass bind interface to http server

---

src/core/index.ts

Fix|Ready
****
missing export HttpServer, HttpsServer in core/index.ts.
[#89 issue](https://github.com/Romakita/ts-express-decorators/issues/89)
```
import { HttpServer, HttpsServer } from "ts-express-decorators";
```

fix(core): missing export httpServer,httpsServer in core/index.ts

---

docs/docs/controllers.md
src/core/class/EntityDescription.ts
src/core/class/Metadata.ts
src/core/class/Store.ts
src/core/utils/index.ts
src/di/services/InjectorService.ts
src/filters/services/FilterService.ts
src/mvc/class/ControllerBuilder.ts
src/mvc/class/ControllerProvider.ts
src/mvc/class/EndpointMetadata.ts
src/mvc/class/HandlerBuilder.ts
src/mvc/registries/EndpointRegistry.ts
src/mvc/registries/ParamRegistry.ts
src/server/class/ServerSettingsProvider.ts
src/server/components/ServerLoader.ts
test/integration/app/app.ts
test/integration/app/controllers/base/BaseController.ts
test/integration/app/controllers/calendars/CalendarCtrl.ts
test/integration/app/controllers/calendars/EventCtrl.ts
test/integration/app/models/Event.ts
test/integration/app/spec/swagger.json
test/integration/rest.spec.ts
test/units/core/class/Metadata.spec.ts
test/units/core/class/Registry.spec.ts
test/units/mvc/class/EndpointBuilder.spec.ts
test/units/mvc/class/EndpointMetadata.spec.ts
test/units/mvc/registries/ParamsRegistry.spec.ts
test/units/server/components/ServerLoader.spec.ts
test/units/testing/bootstrap.spec.ts

---|---|---
Fix & Documentation | Ready | No
****
- Fix EndpointBuilder, ControllerBuilder, ControllerProvider
- Add method Metadata.getOwn(), Metadata.hasOwn
- Fix ServerLoader error
Closes: #91
Ts.ED support the ES6 inheritance class. So you can declare a controller that implement some generic method
and use it on a children class.
To do that just declare a parent controller without the `@Controller` decorator.
```typescript
export abstract class BaseController {
constructor(private someService: SomeService) {}
@Get('/list')
async list(@QueryParams("search") search: any) {
return someService.list(search)
}
}
```
Then, on your children controller:
```typescript
@Controller('/children')
export abstract class ChildrenCtrl extends BaseController {
@Get('/:id') …
```

fix(mvc): Fix building Endpoint when class inherit from a parent class

---

docs/configuration.md
docs/docs/server-loader/versioning.md
src/server/components/ServerLoader.ts
src/server/decorators/serverSettings.ts
src/server/interfaces/IServerSettings.ts
src/servestatic/services/ServeStaticService.ts
test/units/server/components/ServerLoader.spec.ts

---|---|---
Feature | In development | No
****
Closes: #84 
Actually, ServerSettings accept one Glob for one global endpoint.
As a developer, I want to be able to configure a set of files for the same global endpoint.
```typescript
mount: {
'/rest': [
'controllers/accounts/*.js',
'controllers/documents/*.js'
]
}
})
class Server extends ServerLoader {
}
```

feat(server): Allow multiple path for each mounting endpoint

---

src/core/index.ts

In the documentation the import is described as:
import {Store, UseBefore} from "ts-express-decorators";
Hence the Store should be in the Index?

Add Store to Index

---

package.json

It seems importHelpers was added to tsconfig.json but no dependency on tslib was added to package.json?
This seems like a natural dependency else the build will fail.

importHelpers true but no lib dependency?

---

src/mvc/class/ControllerProvider.ts
src/mvc/interfaces/IControllerMiddlewares.ts
src/mvc/interfaces/IControllerOptions.ts
src/mvc/interfaces/index.ts

Currently 2.3.0+ of ts-express-decorators is failing when used.
Fixed by pull request.
Errors in my build:
node_modules/ts-express-decorators/lib/mvc/class/ControllerProvider.d.ts(95,18): error TS2304: Cannot find name 'IControllerMiddlewares'.
node_modules/ts-express-decorators/lib/mvc/interfaces/IControllerOptions.d.ts(16,19): error TS2304: Cannot find name 'IControllerMiddlewares'.

FIX IControllerMiddlewares needs to be exported

---

docs/_coverpage.md

Found on https://romakita.github.io/ts-express-decorators/#/

Fix link to github repo on Ts.ED homepage

---

docs/configuration.md
src/converters/services/ConverterService.ts
src/server/class/ServerSettingsProvider.ts
src/server/decorators/serverSettings.ts
src/server/interfaces/IServerSettings.ts
src/server/services/ServerSettingsService.ts
test/units/converters/services/ConverterService.spec.ts
test/units/server/services/ServerSettings.spec.ts

---|---|---
Featuren | Ready | No
****
Since v1.6, [ConverterService](http://romakita.github.io/ts-express-decorators/docs/converters.md)
check the consistency between the model and the Json object given to the endpoint.
When a property is unknown on the model, Ts.Ed throw a BadRequest.
You can revert it with validationModelStrict options (ServerSettings).
Closes: #146

feat(converter): Add global option validationModelStrict.

---

src/swagger/class/OpenApiEndpointBuilder.ts

fix(swagger): the latest release were not backwards compatible.
It should probably be decided whether all operation specific information should be moved to the dedicated _operation_ namespace, meaning removing all the following (Not backwards compatible):
```typescript
const produces = this.endpoint.get("produces") || [];
const consumes = this.endpoint.get("consumes") || [];
const responses = this.endpoint.get("responses") || {};
const security = this.endpoint.get("security") || {};
```
then one could NOT write:
```typescript
.merge("responses", {"401": {description: "No authorization token was found"}})
.merge("security", [{"Token": [scope]}]);
```
but would have to put everything in the _operation_ namespace:
```typescript
.merge("operation", {
security: [{"Token": [scope]}],
responses: …
```

Fixed missing security definitions

---

src/mvc/components/GlobalErrorHandlerMiddleware.ts
src/mvc/components/LogIncomingRequestMiddleware.ts
src/swagger/class/OpenApiPropertiesBuilder.ts
test/helper/FakeRequest.ts
test/units/mvc/components/GlobalErrorHandlerMiddleware.spec.ts
test/units/mvc/components/LogIncomingRequestMiddleware.spec.ts

chore(logging): moved the request logging to debug instead of info
In an attempt to reduce the ordinary logging the request logging was moved to debug level
@Romakita 
Maybe the real solution would be to split out the request logging in an info part and a debug part. However including the sometimes extreme amounts of data in the info part renders my info logging level worthless :-(

chore(logging): moved to request logging to debug instead of info

---

docs/docs/middlewares/override-middleware.md
docs/docs/services/overview.md
src/core/class/Registry.ts
src/di/decorators/overrideService.ts
src/di/index.ts
src/di/services/InjectorService.ts
src/mvc/decorators/class/overrideMiddleware.ts
test/units/di/decorators/overrideService.spec.ts
test/units/di/decorators/service.spec.ts

---|---|---
****
Add a decorators to override a Service.
The decorator [@OverrideService](api/common/di/overrideservice.md) give you a solution to 
override some embed Ts.ED service like the [ParseService](api/common/filters/parseservice.md).
Example usage:
```typescript
import {OverrideService, ParseService} from "ts-express-decorators"
@OverrideService(ParseService)
class CustomParseService extends ParseService {
}
```

feat(di): Add OverrideService decorator

---

docs/configuration.md
package.json
src/config/class/ServerSettingsProvider.ts
src/config/interfaces/IServerSettings.ts
src/mvc/class/EndpointBuilder.ts
src/mvc/class/HandlerBuilder.ts
src/mvc/components/GlobalErrorHandlerMiddleware.ts
src/mvc/components/LogIncomingRequestMiddleware.ts
src/mvc/index.ts
src/mvc/utils/extendsRequest.ts
src/server/components/ServerLoader.ts
test/helper/FakeRequest.ts
test/units/mvc/class/EndpointBuilder.spec.ts
test/units/mvc/class/HandlerBuilder.spec.ts
test/units/mvc/components/LogIncomingRequestMiddleware.spec.ts
yarn.lock

---|---|---
Fix | Ready | No
****
Fix some problem performance #167
Important things:
- Ts.ED have some feature like dynamic parameters injection which have a cost on the performance. This feature can't be optimized.
- Logger have big cost on the performance. This fix reduce the amount of log per request.
- I've added a logger configuration, to disable completely the log.
Pure Express benchmark
```bash
Benchmarking 127.0.0.1 (be patient)
Server Software:        
Server Hostname:        127.0.0.1
Server Port:            8080
Document Path:          /
Document Length:        11 bytes
Concurrency Level:      20
Time taken for tests:   7.908 seconds
Complete requests:      30000
Failed requests:        0
Keep-Alive requests:    30000
Total transferred:      6450000 …
```

Fix: Performance

---

docs/configuration.md
docs/getting-started.md
package.json
src/config/class/ServerSettingsProvider.ts
src/config/interfaces/IServerSettings.ts
src/core/utils/index.ts
src/di/decorators/inject.ts
src/server/components/ServerLoader.ts
src/server/interfaces/IComponentScanned.ts
test/integration/app/app.ts
test/units/server/components/ServerLoader.spec.ts
yarn.lock

---|---|---
****
- Add ts-node support,
- Controller can be added manually to ServerSettings.mount options,
- Upgrade to TypeScript v2.5
Closes: #172
```
import {} from "ts-express-decorators";
mount: {
"/rest": [
"${rootDir}/controllers/Base/*.js",
"${rootDir}/controllers/calendars/*.ts", // ts-node then fallback to .js extension
RestCtrl // Manual import
],
"/rest/v1": "${rootDir}/controllers/*.ts"
}
})
```
> ServerLoader.mount() is also updated to support all options given in the example.

feat(server): Import manually a controller

---

src/filters/class/FilterBuilder.ts
test/units/filters/class/FilterBuilder.spec.ts

When the decorator `@Required` is used with `@BodyParams`, the value injected
was undefined. https://github.com/Romakita/ts-express-decorators/issues/189
Closes: #189

fix(filter): Undefined value with BodyParams and Required

---

src/socketio/services/SocketIOService.ts
test/units/socketio/services/SocketIOService.spec.ts

---|---|---
Fix | Ready | Yes
****
Fixed a case where using both httpPort and httpsPort socket.io didn't work on the https server.

fix(socketio): allow the possibility to have both httpPort and httpsPort.

---

src/jsonschema/decorators/enum.ts
test/units/jsonschema/decorators/enum.spec.ts

---|---|---
****
Now Enum decorator accept a typescript enum as parameter and build the
right jsonschema.
Closes: #209 
```typescript
enum SomeEnum {
ENUM_1 = "enum1",
ENUM_2 = "enum2"
}
class Model {
@Enum(SomeEnum)
property: SomeEnum;
}
```

feat(jsonschema): Extends Enum decorator

---

docs/docs/controllers.emd
src/common/mvc/class/EndpointBuilder.ts
src/common/mvc/class/EndpointMetadata.ts
src/common/mvc/class/HandlerBuilder.ts
src/common/mvc/constants/index.ts
src/common/mvc/index.ts
src/common/mvc/interfaces/ExpressPathMethod.ts
src/common/mvc/services/ControllerService.ts
src/common/mvc/services/ExpressRouter.ts
src/common/mvc/services/RouteService.ts
src/common/mvc/services/RouterController.ts
src/common/server/decorators/httpServer.ts
src/common/server/decorators/httpsServer.ts
src/swagger/class/OpenApiEndpointBuilder.ts
src/swagger/services/SwaggerService.ts
src/swagger/utils/index.ts
test/integration/app/app.ts
test/integration/app/controllers/RestCtrl.ts
test/units/mvc/class/EndpointBuilder.spec.ts
test/units/swagger/class/OpenApiEndpointBuilder.spec.ts

Now, the decorators `@Get`, `@Post`, `Put`, `Delete`, `@Head` can be used several times
on the same class method.
```typescript
@Controller("/")
export MyCtrl {
@Get("/route1")
@Get("/route2")
async myMethod() {
return {};
}
}
```
It useful when you need to create alias route on the same method.
- Add ExpressRouter decorator (inject Express.Router instance on a controller).
- Deprecate RouterController (use ExpressRouter instead of).
- Deprecate EndpointMetadata.httpMethod, EndpointMetadata.hasHttpMethod and EndpointMetadata.path.
- Fix Regex support on route.
Closes: #255

feat(mvc): Add Multi route support on an Endpoint

---

src/mongoose/utils/buildMongooseSchema.ts
test/units/mongoose/utils/buildMongooseSchema.spec.ts

_id is a reserved key for mongoose but not for the JsonSchema.
Now the _id is filtered when JsonSchema is converted to a mongoose Schema.
Closes: #280

fix(mongoose): Filter _id on generated Schema

---

docs/getting-started.md

tsc was generating warnings about two functions being called the same (post) and about the new promise without type trying to initialize it to an empty object
---|---|---
Doc| Ready | No
****
By copying and pasting the controller, tsc is showing warnings, solved with this commit.

Solving tsc warnings on docs

---

src/common/di/class/Providers.ts

fix the following error message throwing on my CI:
```
node_modules/@tsed/common/lib/di/class/Providers.d.ts(2,29): error TS2307: Cannot find module '../../../core/class/Registry'.
```
this bug was introduced somewhere above version `4.12.4`

fix(typescript): Fix an issue where the .d.ts file cant be found

---

src/common/mvc/class/HandlerMetadata.ts
test/units/mvc/class/HandlerMetadata.spec.ts

Fix problem when a middleware error is override.
Type information is lost in this case.
Closes: #320

fix(mvc): Fix override middleware decorator

---

docs/tutorials/swagger.emd
src/swagger/interfaces/ISwaggerSettings.ts
src/swagger/readme.md
src/swagger/services/SwaggerService.ts
test/units/swagger/services/SwaggerService.spec.ts

- Use outFile option in swagger configuration to write the swagger.json
in a specific directory.

fix(swagger): Restore spec generation.

---

src/common/di/class/Provider.ts
src/common/di/class/Providers.ts
src/common/di/interfaces/ProviderType.ts
src/common/di/interfaces/RegistrySettings.ts
src/common/di/services/InjectorService.ts
src/common/mvc/class/ControllerBuilder.ts
src/common/mvc/class/ControllerProvider.ts
src/common/mvc/class/HandlerBuilder.ts
src/common/mvc/class/HandlerMetadata.ts
src/common/mvc/decorators/class/controller.ts
src/common/mvc/registries/ControllerRegistry.ts
src/common/mvc/services/ControllerService.ts
src/common/mvc/services/RouteService.ts
src/swagger/class/OpenApiEndpointBuilder.ts
src/swagger/services/SwaggerService.ts
test/integration/app/controllers/users/UserCtrl.ts
test/integration/data/swagger.spec.json
test/units/di/services/InjectorService.spec.ts
test/units/mvc/class/ControllerProvider.spec.ts
test/units/mvc/class/EndpointBuilder.spec.ts
test/units/mvc/class/HandlerBuilder.spec.ts
test/units/mvc/class/HandlerMetadata.spec.ts
test/units/mvc/registries/ControllerRegistry.spec.ts
test/units/mvc/services/ControllerService.spec.ts
test/units/swagger/class/OpenApiEndpointBuilder.spec.ts

Now all components (Controllers, Services, Factory, Converters, Model, etc...) are stored in the same registry. 
Next step is to implement containers. This feature will allow to create multiple server instance without side effect.
Unit test will be facilitated.

chore: Refactoring Controllers registry

---

docs/tutorials/socket-io.emd
src/socketio/class/SocketHandlersBuilder.ts
src/socketio/decorators/nsp.ts
src/socketio/interfaces/ISocketProviderMetadata.ts
src/socketio/readme.md
src/socketio/services/SocketIOService.ts
test/units/socketio/class/SocketHandlersBuilder.spec.ts
test/units/socketio/decorators/nsp.spec.ts

Argument given to Nsp decorator allow to inject on the property class (socket service),
a specific namespace (other than the default Namespace used by the socket service).
```typescript
import * as SocketIO from "socket.io";
import {SocketService, IO, Nsp, Socket, SocketSession} from "@tsed/socketio";
@SocketService("/my-namespace")
export class MySocketService {
@Nsp nsp: SocketIO.Namespace;
@Nsp("/my-other-namespace")
nspOther: SocketIO.Namespace; // communication between two namespace
constructor(@IO private io: SocketIO.Server) {}
/**
* Triggered the namespace is created
*/
$onNamespaceInit(nsp: SocketIO.Namespace) {
}
/**
* Triggered when a new client connects to the Namespace.
*/
$onConnection(@Socket socket: SocketIO.Socket, @SocketSession session: SocketSession) {
}
/**
* …
```

feat(socketio): Add argument on Nsp decorator

---

src/mongoose/decorators/ref.ts
test/units/mongoose/decorators/ref.spec.ts

fix(mongoose): Ref decorator support string type for circular dependency

---

src/mongoose/decorators/index.ts
src/mongoose/decorators/mongooseIndex.ts
src/mongoose/decorators/select.ts
src/mongoose/interfaces/MongooseModelOptions.ts
src/mongoose/utils/schemaOptions.ts
test/units/mongoose/decorators/mongooseIndex.spec.ts
test/units/mongoose/decorators/select.spec.ts
test/units/mongoose/utils/schemaOptions.spec.ts

Add two mongoose decorators to:
- define schema indexes
- set default select() behavior for schema path
Calls schema.index() to define an index (most likely compound) for the schema.
```typescript
@Model()
@MongooseIndex({first: 1, second: 1}, {unique: 1})
export class EventModel {
@Property()
first: string;
@Property()
second: string;
}
```
Tells Mongoose to set default select() behavior for this path.
```typescript
@Model()
export class EventModel {
@Select(false)
field: string;
}
```

feat(mongoose): decorators for select and schema.index()

---

docs/tutorials/upload-files-with-multer.md
src/core/utils/getValue.ts
src/core/utils/setValue.ts
src/multipartfiles/components/MultipartFilesFilter.ts
src/multipartfiles/decorators/multerOptions.ts
src/multipartfiles/decorators/multipartFile.ts
src/multipartfiles/index.ts
src/multipartfiles/middlewares/MultipartFileMiddleware.ts
src/multipartfiles/package.json
src/multipartfiles/readme.md
src/swagger/class/OpenApiParamsBuilder.ts
src/swagger/decorators/consumes.ts
test/integration/app/controllers/calendars/CalendarCtrl.ts
test/integration/data/swagger.spec.json
test/units/multipartfiles/decorators/multerOptions.spec.ts
test/units/multipartfiles/decorators/multipartFile.spec.ts
test/units/multipartfiles/filters/MultipartFileFilter.spec.ts
test/units/multipartfiles/middlewares/MultiparFileMiddleware.spec.ts
test/units/swagger/decorators/consumes.spec.ts

- Add name field support (`@MultipartFile('fieldName')`)
- Add `@MulterOptions()` decorator usable on method to configure specific multer options
- Improve Swagger documentation support
Closes: #398 
```typescript
import {Controller, Post} from "@tsed/common";
import {MultipartFile, MulterOptions} from "@tsed/multipartfiles";
@Controller('/')
class MyCtrl {
@Post('/file')
private uploadFile(@MultipartFile('file') file: Express.Multer.File) {
}
@Post('/file')
@MulterOptions({dest: "/other-dir"})
private uploadFile(@MultipartFile('file') file: Express.Multer.File) {
}
}
```

feat(multipartfile): Add field name support for file upload

---

packages/common/src/di/class/Provider.ts
test/units/di/class/Provider.spec.ts

Type | Migration
---|---
Fix | No
****
Provider uses constructor symbol instead of its description. This results in that `InjectorService` creates few instances on one provider. 
See following example:
```typescript
import {InjectorService} from "@tsed/common";
export interface DummyService {
noop(): void;
}
export const DummyService = Symbol("DummyService");
export class DummyServiceImp {}
registerProvider({provide: DummyService, userClass: DummyServiceImp});
export interface DummyService2 {
noop(): void;
}
export const DummyService2 = Symbol("DummyService2");
export class DummyService2Imp {}
registerProvider({provide: DummyService2, userClass: DummyService2Imp});
```
If I try to call `InjectorService.load()` method it builds 2 instances for following class DummyService2Imp and …

fix(di): get symbol description instead of its constructor

---

packages/common/src/config/services/ServerSettingsService.ts
packages/common/test/config/services/ServerSettingsService.spec.ts

- Fix: allow configuration null value
****
Type of null is object but must not be used as an object in settings. This condition allow use of null value in settings.

fix(common): allow configuration null value

---

packages/graphql/src/interfaces/IGraphQLSettings.ts
packages/graphql/src/services/GraphQLService.ts

I added a few more settings:
1. `server` allows to set a custom server via callback (I use a customized server in my project and it would be very useful)
2. `installSubscriptionHandlers` allows to bind httpServer to Apollo Server (it's needed for subscriptions: https://www.apollographql.com/docs/apollo-server/features/subscriptions.html#middleware)
---|---
Feature | No
****
```typescript
import {ServerLoader, ServerSettings} from "@tsed/common";
import {IGraphQLSettings} from "@tsed/graphql"; 
graphql: {
'server1': {
resolvers:[],
installSubscriptionHandlers: true,
server: config => new CustomApolloServer(config)
}
} as IGraphQLSettings
})
export class Server extends ServerLoader {
}
```

feat(graphql): Add support for subscriptions and custom Apollo Server

---

docs/tutorials/graphql.md
packages/graphql/src/interfaces/IGraphQLServer.ts
packages/graphql/src/services/GraphQLService.ts

---|---
Feature | Yes
****
GraphQLService allows to get ApolloServer instance only and it's impossible to get a generated Schema. I changed `_instances` map to object that contains 2 properties currently:
* instance
* schema
Is this fine? Because I'm not sure if it's the best option and maybe there's a better way to do it :)

feat(graphql): Add instance and schema to servers map

---

packages/mongoose/src/decorators/virtualRef.ts
packages/mongoose/src/interfaces/MongooseVirtualRefOptions.ts
packages/mongoose/test/decorators/virtualRef.spec.ts

---|---
Fix | No
****
Fixed issue #546  
Now you can use both ways, passing an options object or two string parameters:
```
export class IAccountData {
public _id?: ObjectId;
@Required()
public type?: String;
@Required()
public key?: String;
@Required()
@Default({})
public value?: Object;
@Ref(IAccount)
@Required()
public account_id?: Ref<IAccount>;
@VirtualRef({type: 'Account', foreignField: '_id', localField: 'account_id', justOne: true})
public account?: VirtualRef<IAccount>;
}
```
Or
```
export class IAccountData {
public _id?: ObjectId;
@Required()
public type?: String;
@Required()
public key?: String;
@Required()
@Default({})
public value?: Object;
@Ref(IAccount)
@Required()
public account_id?: Ref<IAccount>;
@VirtualRef('Account', '_id')
public account?: …
```

Fixed #546

---

packages/mongoose/src/decorators/ref.ts
packages/mongoose/src/interfaces/MongooseSchemaTypes.ts

Feature|No
****
Sometimes you may want to create refs which doesn't reference an object id, instead, you want to reference a string or a number. For this, I added a new parameter to the Ref decorator so anyone can choose the type of the field. If you don't specify any type, it will default to ObjectId, so this won't cause any breaking changes.
```
import {Model, Ref} from "@tsed/mongoose";
@Model()
export class FooClass {
@Ref(OtherClass, MongooseSchemaTypes.STRING)
otherClass: Ref<OtherClass>
}
@Model({schemaOptions: {_id: false}})
export class OtherClass {
@Indexed()
@Required()
@Unique()
_id: string
}
```

Added one more parameter to ref for defining the reference type

---

docs/tutorials/mongoose.md
docs/tutorials/snippets/mongoose/dynamic-references.ts
packages/mongoose/src/decorators/dynamicRef.ts
packages/mongoose/src/decorators/index.ts

feat(mongoose): Added DynamicRef decorator to support mongoose dynamic ref. Issue #567
Feature|No
****
Added a new decorator called DynamicRef to add dynamic refs via refPath property as documented in https://mongoosejs.com/docs/populate.html#dynamic-ref.
```
import {DynamicRef, Model, Enum} from "@tsed/mongoose";
@Model()
class MyModel {
@DynamicRef('model') // The parameter here is the name of the field which will contain the name of the model for mongoose to populate
entity: Ref<OtherModel | FooModel>
@Enum(['OtherModel', 'FooModel'])
model: string
}
```
Then, you can simply populate by the ref field:
```
const myModel = this.MyModel.findById('5d001194df1e1a18ac52bc86').populate('entity') // The entity field will come populated
```
I am not used to do tests and …

feat(mongoose): Added DynamicRef decorator to support mongoose dynamic ref. Issue #567

---

packages/graphql/package.json
packages/graphql/src/decorators/dataSourceService.ts
packages/graphql/src/index.ts
packages/graphql/src/interfaces/IGraphQLSettings.ts
packages/graphql/src/registries/DataSourceServiceRegistry.ts
packages/graphql/src/services/GraphQLService.ts
packages/graphql/test/services/GraphQLService.spec.ts

for #577  
Type
Feature
****
Add a DataSource decorator registry that enables component scanning for Apollo DataSources to be added to the server config automatically (and with DI).
Just tag the services and make sure they are in the component scanning config.
```
import {DataSourceService} from "@tsed/graphql";
import { RESTDataSource } from 'apollo-datasource-rest';
@DataSourceService()
export class MyDataSource extends RESTDataSource {
constructor() {
super();
this.baseURL = 'https://awesome-api.example.com';
}
willSendRequest(request) {
request.headers.set('Authorization', this.context.token);
}
getMyData(id: string) {
return this.get(`/v1/my_rest_data/${id}`);
}
}
```

feat(graphql): add support for component scanned dataSources

---

packages/common/src/converters/services/ConverterService.ts

ConvertService throws internal server error when it fails to convert a decorated property.
The expected behavior is to throw a bad request error.
example: 
When expecting to receive a body param of the following schema:
```
class User {
@Required()
id: number;
}
```
And the HTTP body request contains  
```
{ 
id="sdn12nsf"
} 
```
The expected HTTP response is:
```
{
"status": 400,
"body": "Error for id with value sdn12nsf \nCast error. Expression value is not a number."
}
```
The current HTTP response is:
```
{
"status": 500,
"message": "Internal Server Error - Conversion failed for class \"User\" with object => {\"id\":\"sdn12nsf\"}.\nnewMessage is not defined"
}
```

Throw bad request error when property convert failed on Converter Service

---

packages/common/src/server/components/ServerLoader.ts

---|---
Fix |No
****
The idea of this commit is to remove the command to log out each configured setting. The reason for this is to improve security since TypeOrm - for example - settings are displayed in the logs; this includes passwords and username.
This should not be outputted since it provides an attacker with a way to identify the connections needed. These connection(s) could be access to a critical Production system therefore it should be up to the developer to decide if they wish to write data to the logs.
If needed, the settings object can be accessed from the Server object returned from `ServerLoader.bootstrap()` thus ensuring any decision is thought
Tests run, builds are good and code coverage are as follows:
Tests:  1217 passing (5s)
Statements   : 100% …

Stop outputting the settings

---

docs/.vuepress/config.js
docs/tutorials/jest.md
packages/common/src/server/utils/cleanGlobPatterns.ts
packages/common/test/server/utils/cleanGlobPatterns.spec.ts

---|---
fixes #477 
****
When using `jest` and `ts-jest`, the `require.extensions['.ts']` compiler is not set.
Easy solution, for now, could be to pass an environment variable that will prevent the file extension change.

Added flag to indicate not to switch file extensions

---

packages/common/src/config/interfaces/ILoggerSettings.ts
packages/common/src/server/components/LogIncomingRequestMiddleware.ts
packages/common/test/server/components/LogIncomingRequestMiddleware.spec.ts

Allow configuring whether the "request.start" and "request.end" events show when logging requests
---|---
Feature | No
****
Having both "request.start" and "request.end" inflates our logs too much.
This PR will allow us to reduce the logs by 50%.
```ts
import { ServerLoader, ServerSettings } from '@tsed/common';
...
logger: {
logRequest: true,
logStart: false,
logEnd: true
}
...
})
export default class Server extends ServerLoader {}
```

Allow configuring logger events

---

tasks/gulp/repo.js

---|---
Chore | No
****
There's no point in including source files into `npm` package. It not only affects on a package size, but also can lead to re-compile `.ts` files in `node_modules`.

chore: refuse to include source files into package

---

packages/common/src/server/utils/cleanGlobPatterns.ts

---|---
Fix| No
****
Regression of #603 due to globby dependency, causing build errors on windows as paths resolve with "\" rather than "/"
Currently failing one test need to know if this is the correct fix?

Fix Scanning on Windows Paths

---

docs/getting-started.md

---|---
Doc | No
****
Correct spelling in the Getting Started guide 😄

docs: Correct spelling in Getting Started guide

---

docs/snippets/configuration/bootstrap-with-dotenv.ts

I believe this snippet was copy-pasted from the npm-config example and line 9 was not updated.

Fix dotenv example snippet

---

packages/mongoose/src/decorators/index.ts
packages/mongoose/src/decorators/schemaIgnore.ts
packages/mongoose/src/utils/createSchema.ts
packages/mongoose/test/decorators/mongooseIgnore.spec.ts
packages/mongoose/test/utils/createSchema.spec.ts

---|---
Feature | No
****
Add new decorator ```@SchemaIgnore``` to allow defining properties not entering into mongoose schema.
Useful for serializing virtual fields and mongoose/plugin generated fields.
```
import {Model, SchemaIgnore} from '@tsed/mongoose';
import {Default, Format, Property, PropertyName} from '@tsed/common';
@Model({schemaOptions: {discriminatorKey: 'kind'}})
export class Event {
@PropertyName('id')
_id: string;
@Format('date-time')
@Default(Date.now)
created: Date;
@Property()
@SchemaIgnore()
kind: string;
}
```

Mongoose ignore

---

packages/common/src/config/services/ServerSettingsService.ts
packages/common/test/config/services/ServerSettingsService.spec.ts
tsconfig.json

---|---
Fix|Yes
****
Since `httpPort` and `httpsPort` can be `false` (to disable the respective protocol), I propose adding `false` to the untagged union type of those properties (and the `httpPort` synonym port). The setter and getter of settings.debug disagreed, so I propose changing the getter to return true iff the log level is `"debug"`.
Automate type checking to improve the quality of the type annotations.

Fix getter of debug setting and type annotations of port settings

---

packages/graphql/src/services/GraphQLService.ts

the createDatasources is executed once in the server config, the getDatasources needs to be provider scope instance per request. It needs to be inside the factory call or else the internal caching mechanism of RestDataSource will not be properly flushed and cause a memory leak.

[BUGFIX/GRAPHQL/URGENT] dataSources needs to be instantiated each apollo request

---

packages/common/src/jsonschema/decorators/propertyType.ts

---|---
Fix | No
****
Hi @Romakita, tsed is a great project, thank you to allow us to use it! 
Some weeks ago i was building an express-based project with Typescript, trying to have a similar experience to many MVC frameworks like Spring Boot, adding TypeOrm, DI, Services, AutoMapper and Swagger integration; then i found tsed and it's exactly the project i would like to build! Thank you indeed.
Following the example of #719 i made some minor linguistic improvements to the Property Type documentation. I'm italian, so my english skill could be not be the best available around here, but I believe the changes make the point more clear.

fix: propertyType doc improvements

---

packages/swagger/package.json

Fix
****
Package "@tsed/swagger"
The typings file name is wrongly pointing to `./lib/index.ts` (which does not exists) creating a tsc compilation error
```
error TS7016: Could not find a declaration file for module '@tsed/swagger'. '..../node_modules/@tsed/swagger/lib/index.js' implicitly has an 'any' type.
Try `npm install @types/tsed__swagger` if it exists or add a new declaration (.d.ts) file containing `declare module '@tsed/swagger';`
3 import {Description, Example} from "@tsed/swagger";
```

Fix typings path ("@tsed/swagger")

---

packages/platform-test-utils/src/tests/testView.ts

Fix PlatformExpress - View - Scenario1: GET /rest/views/scenario-1 -
should render a view from #953
---|---
Fix | No
****
Fix Windows tests compatibility

fix(platform-test-utils): replace \n with EOL in response matching

---

packages/platform-express/src/interfaces/PlatformExpressStaticsOptions.ts
packages/platform-express/src/interfaces/index.ts
packages/platform-express/src/services/PlatformExpressApplication.ts
packages/platform-express/src/services/PlatformExpressRouter.ts

Merge automatically express params when using Platform Express and Express.Router.
Express.js:
> Preserve the req.params values from the parent router. If the parent and the child have conflicting param names, the child’s value take precedence.

Fix express merge params behavior

---

docs/getting-started/README.md
docs/getting-started/create-your-first-controller.md
docs/getting-started/migration-from-v5.md
docs/getting-started/start-with-cli.md

Fix typos in README

---

packages/common/src/converters/components/MapConverter.ts
packages/common/src/converters/components/SetConverter.ts
packages/common/src/converters/services/ConverterService.ts
packages/common/src/platform/domain/ControllerProvider.spec.ts
packages/core/src/decorators/enumerable.spec.ts
packages/core/src/interfaces/HashOf.ts
packages/core/src/utils/ObjectUtils.ts
packages/core/src/utils/cleanObject.ts
packages/core/src/utils/deepExtends.spec.ts
packages/core/src/utils/deepExtends.ts
packages/core/src/utils/getEnumerableKeys.spec.ts
packages/core/src/utils/getEnumerableKeys.ts
packages/core/src/utils/index.ts
packages/core/src/utils/isEnumerable.ts
packages/core/src/utils/isProtectedKey.spec.ts
packages/core/src/utils/isProtectedKey.ts
packages/core/src/utils/objectKeys.spec.ts
packages/core/src/utils/objectKeys.ts
packages/core/src/utils/setValue.spec.ts
packages/core/src/utils/setValue.ts
packages/di/src/class/Provider.spec.ts
packages/di/src/class/Provider.ts
packages/json-mapper/src/components/MapMapper.ts
packages/json-mapper/src/components/SetMapper.ts
packages/json-mapper/src/utils/deserialize.ts
packages/mongoose/src/utils/cleanProps.ts
packages/mongoose/src/utils/createSchema.ts

---|---
Fix | No
****
Prevent prototype pollution when using deepExtends function, converterService or @tsed/json-mapper functions.

Fix security proto pollution

---

examples/typeorm/src/Server.ts
packages/json-mapper/src/utils/serialize.spec.ts
packages/json-mapper/src/utils/serialize.ts

Fix issue when any schema decorators are used on properties
```typescript
class User {
@log()
myProp: string =  "myProp";
} 
// before fix
serialize(new User())  // {}
// after fix
serialize(new User())  // {myProp: "myProp"}
```
Closes: #1016

fix(json-mapper): Discover Model properties when any decorators are used on property

---

packages/schema/src/utils/getJsonSchema.spec.ts
packages/schema/src/utils/serializeJsonSchema.ts

Required field is correctly generated when there is inheritance with a mixin
Closes: #1030
```typescript
it("should keep required meta from inherited class", () => {
// WHEN
const AutoUUID = <T extends Type<any>>(Base: T) => {
class AutoUUIDMixin extends Base {
@Property() //showing up in swagger as a property
@Format("uuid") //showing up as a uuid in swagger
@Required(true)
id: string;
}
return AutoUUIDMixin;
};
const WithDates = <T extends Type<any>>(Base: T) => {
class WithDates extends Base {
@Property() //showing up in swagger as a property
@Format("datetime") //showing up as a uuid in swagger
@Required(true)
created_at: string;
@Property() //showing up in swagger as a property
@Format("datetime") //showing up as a uuid in swagger
@Required(true)
updated_at: string;
}
return …
```

fix(schema): Fix Required metadata with schema inheritance

---

packages/json-mapper/src/utils/serialize.spec.ts
packages/json-mapper/src/utils/serialize.ts
packages/json-mapper/test/integration/ignore.integration.spec.ts
packages/platform-test-utils/src/tests/testResponse.ts

fix(#1057): Value returned by an endpoint without @Returns is now correctly serialized

---

docs/tutorials/swagger.md
packages/schema/src/utils/operationIdFormatter.ts
packages/swagger/readme.md
packages/swagger/src/interfaces/SwaggerSettings.ts
packages/swagger/src/services/SwaggerService.ts
packages/swagger/test/swaggger.operationId.spec.ts

Closes: #1064
---|---
Feature  | No
****
```typescript
import "@tsed/swagger";
@Configuration({
swagger: [{
operationIdFormatter: () => {},
operationIdPattern: "%c_%m"
}]
})
```

feat(swagger): Add operationIdPattern and operationIdFormatter option to swagger

---

docs/docs/configuration.md
packages/common/src/index.ts
packages/di/src/index.ts
packages/di/src/services/DILogger.spec.ts
packages/di/src/services/DILogger.ts

---|---
Feat/Chore | No
****
Logger can be injected to another service.
```typescript
import {Logger} from "@tsed/logger";
import {Injectable} from "@tsed/di";
@Injectable()
export class MyService {
@Inject()
logger: Logger;
}
```

Feat logger

---

packages/platform-express/test/pageable.spec.ts
packages/schema/src/domain/JsonParameter.ts
packages/schema/src/utils/getSpec.spec.ts
packages/schema/test/helpers/validateSpec.ts
packages/schema/test/pageable.integration.spec.ts

---|---
Fix | No
****
Fix OS3 spec generation when a model is used as QueryParams Type
See: https://gist.github.com/Romakita/2dd599b6905a08ab0301414599c3858a

fix(schema): Fix issue on OS3 when using a model as QueryParams type

---

docs/docs/snippets/providers/getting-started-injectable.ts

---|---
Doc | No
****
Correct the provider type to `ProviderType.SERVICE` in the sample snippet of how to use `@Injectable` for services. The previous version had `ProviderType.CONTROLLER` and would throw an `INJECTION_ERROR` with `TypeError: provider.hasParent is not a function`.

docs: fix provider type in injectable service snippet

---

packages/platform-express/test/pageable.spec.ts
packages/schema/src/decorators/common/allOf.spec.ts
packages/schema/src/decorators/common/allOf.ts
packages/schema/src/decorators/common/anyOf.spec.ts
packages/schema/src/decorators/common/anyOf.ts
packages/schema/src/decorators/common/oneOf.spec.ts
packages/schema/src/decorators/common/oneOf.ts
packages/schema/src/decorators/common/schema.ts
packages/schema/src/decorators/index.ts
packages/schema/src/domain/JsonSchema.ts
packages/schema/src/utils/from.spec.ts
packages/schema/src/utils/from.ts
packages/schema/src/utils/serializeJsonSchema.ts
packages/schema/test/pageable.integration.spec.ts

---|---
Feature | No
****
Update functional JsonSchema declaration utils:
```typescript
import {
CollectionOf,
Default,
Description,
Integer,
MaxItems,
Min,
MinLength,
Property,
Required,
For,
SpecTypes,
oneOf,
string,
array
} from "@tsed/schema";
import {OnDeserialize} from "@tsed/json-mapper";
import {isArray} from "@tsed/core";
class Pageable {
@Integer()
@Min(0)
@Default(0)
@Description("Page number.")
page: number = 0;
@Integer()
@Min(1)
@Default(20)
@Description("Number of objects per page.")
size: number = 20;
@For(SpecTypes.JSON, oneOf(string(), array().items(string()).maxItems(2)))
@For(SpecTypes.OPENAPI, array().items(string()).maxItems(2))
@For(SpecTypes.SWAGGER, array().items(string()).maxItems(2))
@OnDeserialize((value: string | string[]) => …
```

feat(schema): Add @AnyOf, @AllOf, @OneOf and @For decorators

---

packages/graphql/src/decorators/resolverService.ts

---|---
Fix| No
****
This PR changes the type of the `ResolverService `options from `ResolverClassOptions` to `AbstractClassOptions`, since in the newer versions of `type-graphql` there is no `ResolverClassOptions` exported anymore and this causes errors when fresh installing `type-graphql` and trying to build the project.

fixed ResolverService decorator using wrong options type

---

docs/docs/custom-endpoint-decorators.md
docs/docs/middlewares.md
packages/common/src/mvc/decorators/method/acceptMime.spec.ts
packages/common/src/mvc/decorators/method/acceptMime.ts
packages/common/src/mvc/middlewares/AcceptMimesMiddleware.spec.ts
packages/common/src/mvc/middlewares/AcceptMimesMiddleware.ts
packages/common/src/mvc/models/EndpointMetadata.ts
packages/common/src/platform/builder/PlatformControllerBuilder.spec.ts
packages/common/src/platform/builder/PlatformControllerBuilder.ts
packages/common/src/platform/index.ts
packages/common/src/platform/middlewares/GlobalAcceptMimesMiddleware.spec.ts
packages/common/src/platform/middlewares/GlobalAcceptMimesMiddleware.ts
packages/common/src/platform/middlewares/PlatformAcceptMimesMiddleware.spec.ts
packages/common/src/platform/middlewares/PlatformAcceptMimesMiddleware.ts
packages/platform-test-utils/src/tests/testAcceptMime.ts
test/helper/FakeRequest.ts

---|---
Fix | No
****
Fix conflict between GlobalAcceptMimesMiddleware and AcceptMimesMiddleware.
Now, Ts.ED will use only one middleware to check the acceptable mimes (with PlatformAcceptMimesMiddleware).

Fix 1125 accept middlewares

---

readme.md

---|---
Doc | No
****
Fix the getting started link. The current link is https://tsed.io/getting-started.html which response with a 404. I updated it with https://tsed.io/getting-started.

docs: Fix getting started link

---

packages/common/src/platform-response-filter/services/PlatformResponseFilter.ts
packages/platform-express/test/plainText.spec.ts
packages/platform-test-utils/src/tests/testResponse.ts

---|---
Fix | No
Ts.ED consume the accept header to find the best content-type. But if accept is */*, the content-type response isn't correctly applied. This fix solve the issue and let Express/Koa to decide to apply the best content-type based on the response data.
See: https://github.com/Romakita/tsed-issue-1222/issues/1

Fix 1222 response filter

---

docs/docs/snippets/validation/class-validator-pipe.ts

---|---
Fix | No
****
Fix a call to a missing deprecated method in class validation pipe

fix: call to deprecated shouldValidate method

---

packages/mongoose/src/decorators/model.ts
packages/mongoose/src/decorators/ref.ts
packages/mongoose/src/decorators/schema.ts
packages/mongoose/src/utils/createModel.ts
packages/mongoose/src/utils/createSchema.spec.ts
packages/mongoose/src/utils/createSchema.ts
packages/mongoose/test/circularRef.integration.spec.ts
packages/mongoose/test/helpers/models/Contract.ts
packages/mongoose/test/helpers/models/Customer.ts
packages/mongoose/test/subdocument.integration.spec.ts
packages/schema/src/domain/JsonLazyRef.ts
packages/schema/src/domain/JsonSchema.ts
packages/schema/src/domain/index.ts
packages/schema/src/utils/from.ts
packages/schema/src/utils/serializeJsonSchema.ts

---|---
Fix | No
Fix issue when using two classes which reference each other.
```typescript
import {Model, ObjectID, Ref} from "../../../src";
import {TestCustomer} from "./Customer";
@Model({name: "testContract", schemaOptions: {timestamps: true}})
export class TestContract {
@ObjectID()
_id: string;
@Ref(() => TestCustomer)
customer: Ref<TestCustomer>;
} 
```
```typescript
import {Model, ObjectID, Ref} from "@tsed/mongoose";
import {CollectionOf} from "@tsed/schema";
import {TestContract} from "./Contract";
@Model({name: "testCustomer", schemaOptions: {timestamps: true}})
export class TestCustomer {
@ObjectID()
_id: string;
@Ref(() => TestContract)
@CollectionOf(() => TestContract)
contracts?: Ref<TestContract>[];
}
```

Fix mongoose circular ref

---

docs/tutorials/snippets/passport/acceptRoles.ts

---|---
Doc| No
****
Small clean up on the passport tutorial roles snippet:
* Incorrect import
* Switch to use non deprecated function
N/A

Fix import error and deprecated method in example

---

docs/docs/configuration.md
docs/docs/middlewares.md
docs/getting-started/snippets/base/package.json
docs/release.md
package.json
packages/common/src/config/interfaces/index.ts
packages/common/src/platform-builder/builder/PlatformBuilder.ts
packages/core/src/utils/proxyDelegation.ts
packages/passport/src/middlewares/PassportMiddleware.ts
packages/platform-express/test/app/Server.ts
yarn.lock

Provide a middleware list (Express.js, Ts.ED, Koa, etc...) which must be loaded on the `$beforeRoutesInit` hook or on the specified hook.
In addition, it's also possible to configure the `environment` for which the middleware should be loaded.
Here is an example to load middlewares with the previous version (this example will be always available!):
```typescript
import {Configuration, ProviderScope, ProviderType} from "@tsed/di";
import {Env} from "@tsed/core";
@Configuration({})
export class Server {
$afterInit(){
this.app.use(helmet({contentSecurityPolicy: false}))
}
$beforeRoutesInit() {
if (this.env === Env.PROD) {
this.app.use(EnsureHttpsMiddleware);
}
this.app
.use(cors())
.use(cookieParser())
.use(compress({}))
.use(methodOverride())
.use(bodyParser.json()) …
```

feat(common): Add middlewares options to the Server configuration.

---

packages/di/src/decorators/intercept.ts
packages/di/src/interfaces/InterceptorContext.ts
packages/di/src/interfaces/InterceptorMethods.ts

Now InterceptorContext accept a second generic type.
```typescript
export interface InterceptorContext<Klass = Type, Opts = any> {
target: Klass;
propertyKey: string;
args: unknown[];
next: InterceptorNext;
options?: Opts;
}
```

fix(di): Update InterceptorContext interface

---

packages/mongoose/src/services/MongooseService.ts

Now, MongooseService create the default connexion with mongoose.connect, then use mongoose createConnection for other database

fix(mongoose): Fix mongoose connection creation

---

CONTRIBUTING.md
packages/common/src/platform/utils/createContext.spec.ts
packages/common/src/platform/utils/createContext.ts

---|---
Feature | No
Fix | Yes
Chore | Yes
****
Defaults the X-Request-ID header in the response to the incoming request's X-Request-ID header, if it exists.
Also saw a couple of minor issues in the CONTRIBUTING.md doc that I updated while I was here.

Issue 1282

---

packages/json-mapper/src/utils/serialize.spec.ts
packages/json-mapper/src/utils/serialize.ts
packages/mongoose/test/helpers/models/User.ts
packages/mongoose/test/resources.integration.spec.ts

Mongoose wrap array to a CoreMongooseArray which isn't recognized by the json-mapper. To solve it, json-mapper test also the type of the object and infer the type as an ArrayLike.
Closes: #1290

fix(json-mapper): Fix serialization issue with CoreMongooseArray

---

packages/common/src/platform-cache/interceptors/PlatformCacheInterceptor.ts
packages/platform-test-utils/src/tests/testCache.ts

---|---
Fix | No
****
The `max-age` value of the `cache-control` header should be a relative value to the request's time not an absolute timestamp.
Ie. to cache something for 30 seconds should have `cache-control: max-age=30`
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#expiration
https://www.keycdn.com/blog/http-cache-headers#:~:text=downloaded%20every%20time.-,max%2Dage,for%20the%20next%2090%20seconds.
Nothing changes in the usage.

fix: use seconds instead of expires for cache-control max-age value

---

packages/typeorm/src/TypeORMModule.ts
packages/typeorm/src/services/TypeORMService.spec.ts
packages/typeorm/src/services/TypeORMService.ts
packages/typeorm/src/utils/createConnection.spec.ts
packages/typeorm/src/utils/createConnection.ts
packages/typeorm/test/integration.spec.ts

---|---
Fix | No
****
- refs #1332 
- This PR will fix only the first point
- https://github.com/TypedProject/tsed/issues/1332#issuecomment-813404171

fix(typeorm): Support TypeORM ConnectionOptions without name property

---

packages/swagger/views/index.ejs

If swagger ui isn't exposed to / the redirect uri query param should be correctly after this fix.
---|---
Fix | No
****

fix(swagger): Fix oauth2 redirect

---

packages/schema/src/decorators/generics/genericOf.spec.ts
packages/schema/src/decorators/generics/genericOf.ts
packages/schema/src/decorators/operations/returns.spec.ts
packages/schema/src/decorators/operations/returns.ts
packages/schema/src/utils/generics.ts
packages/schema/src/utils/serializeJsonSchema.ts

Example1:
```typescript
@Generics("T")
class Submission<T> {
@Property()
_id: string;
@Property("T")
data: T;
}
enum MyEnum {
READ = "read",
WRITE = "write"
}
class Content {
@GenericOf(MyEnum)
submission: Submission<MyEnum>;
}
```
Example2:
```typescript
@Generics("T")
class Submission<T> {
@Property()
_id: string;
@Property("T")
data: T;
}
enum MyEnum {
READ = "read",
WRITE = "write"
}
class Content {
@GenericOf(string().enum(["read", "write"]))
submission: Submission<MyEnum>;
}
```
Closes: #1347

feat(schema): Support enum and jsonSchema builder given to GenericOf and Returns.Of

---

packages/schema/src/decorators/index.ts

---|---
Fix | No
****
Add missing export for the ForwardGroups decorator to schema.
```typescript
import { ForwardGroups } from "@tsed/schema";
```

fix(schema): Add missing export for the ForwardGroups decorator

---

packages/ajv/src/services/AjvService.ts
packages/json-mapper/src/utils/deserialize.spec.ts
packages/platform-test-utils/src/tests/testBodyParams.ts

Since Ajv touch value in validated data, we need to clone deep the value before validate it.

fix(ajv): clone value before validate data

---

docs/getting-started/README.md

Removed duplicate OIDC tutorial link from the getting started readme.md document
---|---
**Doc** | **No**
****
This is a documentation fix for the getting started section in TSed
N/A

Removed duplicate OIDC tutorial link

---

packages/socketio/src/SocketIOModule.ts
packages/socketio/src/interfaces/index.ts

---|---
Fix | No
****
- This issue caused in v6.39.1 or above with socket.io@^4.
- In socket.io >= 3.0.0, attach method requires `Partial<ServerOptions>` at the second param.
- [v3.0.0](https://github.com/socketio/socket.io/blob/3.0.0/lib/index.ts#L335)
- [v4.0.1(latest)](https://github.com/socketio/socket.io/blob/4.0.1/lib/index.ts#L378)
- However Ts.ED socketio module's configuration type is `ServerOptions`
- This mandatories to users to specify all required properties of `ServerOptions` in `@Configuration`.
- ![image](https://user-images.githubusercontent.com/1638767/116824449-4d605d00-abc5-11eb-8d86-4555d457e04a.png)
- But it is not necessary.
- I don't know why [the server for test](https://github.com/TypedProject/tsed/blob/production/packages/socketio/test/app/ …

fix(socketio): modify type of settings to Partial<ServerOptions>

---

packages/mongoose/src/decorators/mongooseIndexes.spec.ts
packages/mongoose/src/decorators/mongooseIndexes.ts

---|---
Feature | No
****
Define multiple mongoose schema indexes:
```typescript
@Model()
@MongooseIndexes([{fields: {first: 1, second: 1}, options:{unique: 1}}, {fields: {first: 1, third: 1}, options:{unique: 1}}])
export class EventModel {
@Property()
first: string;
@Property()
second: string;
@Property()
third: string;
}
```

feat(mongoose): adding mongooseIndexes decorator

---

docs/tutorials/mongoose.md
docs/tutorials/snippets/mongoose/decimal-numbers.ts
docs/tutorials/snippets/mongoose/extended-decimal-numbers.ts
packages/mongoose/package.json
packages/mongoose/src/decorators/index.ts
packages/mongoose/src/decorators/numberDecimal.spec.ts
packages/mongoose/src/decorators/numberDecimal.ts

I've implemented a ``NumberDecimal`` decorator which can be used to set mongoose's Decimal128 type for number fields.
Looking forward to your feedback!
---|---
Feature | No
****
```typescript
import {Property} from "@tsed/schema";
import {Model, NumberDecimal, Decimal128} from "@tsed/mongoose";
@Model()
export class ProductModel {
@ObjectID("id")
_id: string;
@Property()
sku: string;
@NumberDecimal()
price: Decimal128;
}
```
or alternatively using custom implementation, e.g. big.js:
```typescript
import Big from "big.js"
@Model()
export class PriceModel {
@NumberDecimal(Big)
price: Big;
}
```

feat(mongoose): Add decorator NumberDecimal to support Decimal128 values

---

docs/tutorials/mongoose.md
docs/tutorials/socket-io.md

docs: Fix path issue on documentation
